/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type { FormatCodeSettings, SourceFile } from 'ts-morph';
import type { Logger } from '../api/logger';
import { applyTypeOnlyImports } from './typeOnlyImports';
import { verifyGeneratedCode } from './verification';

/**
 * The first line of every generated file. "Code generated … DO NOT EDIT." is
 * the marker tools recognise as generated code.
 */
const GENERATED_FILE_HEADER =
  '// Code generated by wow-generator. DO NOT EDIT.\n\n';

/**
 * Formatting of the generated code: two-space indentation, single quotes and
 * semicolons, as Prettier's defaults close to what the rest of a TypeScript
 * project uses.
 */
const FORMAT_SETTINGS: FormatCodeSettings = {
  indentSize: 2,
  tabSize: 2,
  convertTabsToSpaces: true,
  semicolons: 'insert' as FormatCodeSettings['semicolons'],
  insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces: true,
};

/**
 * Finishes the files a generation wrote: formats them, organizes and types
 * their imports, checks that the result declares or imports every name it
 * uses, and adds the generated-file header.
 *
 * Imports are written explicitly while generating, never inferred from
 * whatever the output directory happens to resolve, so the output is the
 * same wherever it is written.
 *
 * @param sourceFiles - The files to finish, each written by this generation
 * @param logger - Receives a debug line for each file
 * @throws Error listing each diagnostic when the code does not compile
 */
export function finalizeSourceFiles(
  sourceFiles: readonly SourceFile[],
  logger: Logger,
): void {
  sourceFiles.forEach((sourceFile, index) => {
    logger.debug(
      `Optimizing file [${sourceFile.getFilePath()}] - ${index + 1}/${sourceFiles.length}`,
    );
    sourceFile.formatText(FORMAT_SETTINGS);
    sourceFile.organizeImports(FORMAT_SETTINGS);
  });
  applyTypeOnlyImports(sourceFiles);
  verifyGeneratedCode(sourceFiles);
  for (const sourceFile of sourceFiles) {
    sourceFile.insertText(0, GENERATED_FILE_HEADER);
  }
}
