/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { describe, expect, it, vi } from 'vitest';
import type { ClassDeclarationStructure } from 'ts-morph';
import { Scope, StructureKind } from 'ts-morph';
import type { ModuleBuilder } from '../../src/emit/moduleBuilder';
import {
  DECORATOR_MODULE_SPECIFIER,
  DECORATOR_NAMED_IMPORTS,
  STREAM_RESULT_EXTRACTOR_METADATA,
  addImportDecorator,
  createDecoratorClass,
  addApiMetadataCtor,
} from '../../src/client';

// Mock the import helpers
vi.mock('../../src/emit/imports', () => ({
  addImport: vi.fn(),
}));

describe('decorators', () => {
  describe('constants', () => {
    it('should have correct DECORATOR_MODULE_SPECIFIER', () => {
      expect(DECORATOR_MODULE_SPECIFIER).toBe('@ahoo-wang/fetcher-decorator');
    });

    it('should have correct DECORATOR_NAMED_IMPORTS', () => {
      expect(DECORATOR_NAMED_IMPORTS).toEqual([
        'ApiMetadata',
        'ApiMetadataCapable',
        'ParameterRequest',
        'api',
        'get',
        'post',
        'put',
        'patch',
        'del',
        'request',
        'attribute',
        'path',
        'query',
        'header',
        'body',
        'autoGeneratedError',
      ]);
    });

    it('should have correct STREAM_RESULT_EXTRACTOR_METADATA', () => {
      expect(STREAM_RESULT_EXTRACTOR_METADATA).toBe(`{
  headers: { Accept: ContentTypeValues.TEXT_EVENT_STREAM },
  resultExtractor: JsonEventStreamResultExtractor,
}`);
    });
  });

  describe('addImportDecorator', () => {
    it('should call addImport with correct parameters', async () => {
      const module = {} as ModuleBuilder;
      const { addImport } = vi.mocked(await import('../../src/emit/imports'));

      addImportDecorator(module);

      expect(addImport).toHaveBeenCalledWith(
        module,
        DECORATOR_MODULE_SPECIFIER,
        DECORATOR_NAMED_IMPORTS,
      );
    });
  });

  describe('createDecoratorClass', () => {
    it('should create class with api decorator and no args', () => {
      const module = { add: vi.fn(statement => statement) };
      const className = 'TestClass';

      const result = createDecoratorClass(
        className,
        module as unknown as ModuleBuilder,
      );

      expect(module.add).toHaveBeenCalledWith({
        kind: StructureKind.Class,
        name: className,
        isExported: true,
        typeParameters: [],
        decorators: [
          {
            name: 'api',
            arguments: [],
          },
        ],
      });
      expect(result).toBe(module.add.mock.results[0].value);
    });

    it('should create class with api decorator and args', () => {
      const module = { add: vi.fn(statement => statement) };
      const className = 'TestClass';
      const apiArgs = ['arg1', 'arg2'];

      createDecoratorClass(
        className,
        module as unknown as ModuleBuilder,
        apiArgs,
        ['R = CommandResult'],
        'Base',
      );

      expect(module.add).toHaveBeenCalledWith({
        kind: StructureKind.Class,
        name: className,
        isExported: true,
        typeParameters: ['R = CommandResult'],
        extends: 'Base',
        decorators: [
          {
            name: 'api',
            arguments: apiArgs,
          },
        ],
      });
    });
  });

  describe('addApiMetadataCtor', () => {
    it('should add implements and constructor with required parameter', () => {
      const declaration: ClassDeclarationStructure = {
        kind: StructureKind.Class,
        name: 'Client',
      };

      addApiMetadataCtor(declaration);

      expect(declaration.implements).toEqual(['ApiMetadataCapable']);
      expect(declaration.properties).toBeUndefined();
      expect(declaration.ctors).toEqual([
        {
          parameters: [
            {
              name: 'apiMetadata',
              type: 'ApiMetadata',
              hasQuestionToken: true,
              scope: Scope.Public,
              isReadonly: true,
            },
          ],
        },
      ]);
    });

    it('merges apiMetadata over defaults, so a partial one keeps them', () => {
      const declaration: ClassDeclarationStructure = {
        kind: StructureKind.Class,
        name: 'Client',
        implements: ['Other'],
      };

      addApiMetadataCtor(declaration, '...DEFAULTS');

      expect(declaration.implements).toEqual(['Other', 'ApiMetadataCapable']);
      expect(declaration.properties).toEqual([
        {
          name: 'apiMetadata',
          type: 'ApiMetadata',
          isReadonly: true,
        },
      ]);
      expect(declaration.ctors).toEqual([
        {
          parameters: [
            {
              name: 'apiMetadata',
              type: 'ApiMetadata',
              hasQuestionToken: true,
            },
          ],
          statements: 'this.apiMetadata = { ...DEFAULTS, ...apiMetadata };',
          docs: [
            '@param apiMetadata - Merged over the defaults, so passing only a `fetcher` keeps the base path.',
          ],
        },
      ]);
    });
  });
});
