apiVersion: v1
kind: ConfigMap
metadata:
  name: compensation-service-config
data:
  application.yaml: >-
    management:
      endpoint:
        health:
          show-details: always
          probes:
            enabled: true
      endpoints:
        web:
          exposure:
            include:
              - health
              - cosid
              - cosidGenerator
              - cosidStringGenerator
    springdoc:
      show-actuator: true
    logging:
      level:
        me.ahoo.wow: debug
    spring:
      application:
        name: compensation-service
      web:
        resources:
          static-locations: file:./browser/
      jackson:
        serialization:
          write-durations-as-timestamps: true
          write-dates-as-timestamps: true
        mapper:
          accept-case-insensitive-enums: true
        autoconfigure:
          exclude:
            - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
      elasticsearch:
        username: elastic
        password: elastic
        uris: dev-es-default.dev.svc.cluster.local:9200
      data:
        mongodb:
          uri: mongodb://root:root@localhost:27017/?authSource=admin&maxIdleTimeMS=60000
          database: compensation_db
        redis:
          cluster:
            max-redirects: 3
            nodes:
                - redis-test-redis-cluster-0.redis-test-redis-cluster-headless.test.svc.cluster.local:6379
          password: VPI7MsrrF7beIg
    cosid:
      machine:
        enabled: true
        distributor:
          type: redis
      generator:
        enabled: true
    wow:
      kafka:
        bootstrap-servers: 'kafka-test-0.kafka-test-headless.test.svc.cluster.local:9093'
      eventsourcing:
        store:
          storage: redis
        snapshot:
          storage: elasticsearch