apiVersion: v1
kind: Service
metadata:
  name: wow-compensation-svc
spec:
  selector:
    app: compensation-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: http

---

apiVersion: v1
kind: Service
metadata:
  name: wow-compensation-node-port
spec:
  type: NodePort
  selector:
    app: compensation-service
  ports:
    - nodePort: 32768
      port: 80
      protocol: TCP
      targetPort: http

