/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { ContentTypeValues, type ResultExtractor } from '@ahoo-wang/fetcher';
import {
  JsonEventStreamResultExtractor,
  type JsonServerSentEvent,
} from '@ahoo-wang/fetcher-eventstream';
import { CommandStage } from './command/types.js';
import type { CommandResult } from './command/commandResult.js';
import { isErrorInfo, WowError } from './types/wowError.js';

/**
 * The event name the server gives the rows of a query stream. Wow sends them
 * without an `event:` field, which the event-stream parser reads as
 * `message`.
 */
const ROW_EVENT = 'message';

const COMMAND_STAGES: ReadonlySet<string> = new Set(
  Object.values(CommandStage),
);

/**
 * Passes the events `isData` accepts and errors the stream with a `WowError`
 * at the first one it does not.
 *
 * When a server-sent event stream fails midway, Wow still answers HTTP 200
 * and sends one last event whose name is the error code and whose data is
 * the `ErrorInfo`, then closes the stream (`WebFluxResponseStrategy`,
 * `errorResume`). Read as data it would pass for a row or a command result;
 * here it ends the stream the way a failed request ends a call.
 */
function failOnErrorEvent<T>(
  isData: (eventName: string) => boolean,
): TransformStream<JsonServerSentEvent<unknown>, JsonServerSentEvent<T>> {
  return new TransformStream({
    transform(event, controller) {
      if (isData(event.event)) {
        controller.enqueue(event as JsonServerSentEvent<T>);
        return;
      }
      controller.error(
        new WowError(
          isErrorInfo(event.data)
            ? event.data
            : { errorCode: event.event, errorMsg: '' },
        ),
      );
    },
  });
}

/**
 * The result extractor of the query streams (`listStream`,
 * `listStateStream`, `aggregateStream`, …): the response as a stream of JSON
 * server-sent events, which errors with a {@link WowError} when the server
 * sends an error event.
 */
export const QueryEventStreamResultExtractor: ResultExtractor<
  ReadableStream<JsonServerSentEvent<any>>
> = async exchange =>
  (await JsonEventStreamResultExtractor(exchange)).pipeThrough(
    failOnErrorEvent(eventName => eventName === ROW_EVENT),
  );

/**
 * The result extractor of `sendAndWaitStream`: the command results, one per
 * stage the command reached, which errors with a {@link WowError} when the
 * server sends an error event. A command result whose own `errorCode` is not
 * `Ok` is still a result — the command failed in its processing — and is
 * passed on as one.
 *
 * Generated command clients can take it as their `resultExtractor`.
 */
export const CommandResultEventStreamResultExtractor: ResultExtractor<
  ReadableStream<JsonServerSentEvent<CommandResult>>
> = async exchange =>
  (await JsonEventStreamResultExtractor(exchange)).pipeThrough(
    failOnErrorEvent<CommandResult>(eventName => COMMAND_STAGES.has(eventName)),
  );

/**
 * The endpoint options of a command whose answer is a server-sent event
 * stream: `Accept: text/event-stream`, and
 * {@link CommandResultEventStreamResultExtractor}, which errors the stream
 * with a {@link WowError} at the server's error event.
 * `CommandClient.sendAndWaitStream` uses it.
 *
 * A decorated command client that streams, hand-written or generated, takes
 * it whole instead of spelling out the header and the extractor, so the
 * transport is defined in one place. It fits both `@api` and the endpoint
 * decorators. It is frozen; spread it to add options.
 *
 * @example
 * ```typescript
 * import { api, autoGeneratedError, post, request } from '@ahoo-wang/fetcher-decorator';
 *
 * interface AddCartItem {
 *   productId: string;
 * }
 *
 * // Every endpoint of the class streams.
 * @api('cart', COMMAND_STREAM_ENDPOINT)
 * class CartStreamCommandClient {
 *   @post('add_cart_item')
 *   addCartItem(
 *     @request() command: CommandRequest<AddCartItem>,
 *   ): Promise<CommandResultEventStream> {
 *     throw autoGeneratedError(command);
 *   }
 * }
 *
 * // One endpoint streams.
 * @api('cart')
 * class CartCommandClient {
 *   @post('add_cart_item', COMMAND_STREAM_ENDPOINT)
 *   addCartItemStream(
 *     @request() command: CommandRequest<AddCartItem>,
 *   ): Promise<CommandResultEventStream> {
 *     throw autoGeneratedError(command);
 *   }
 * }
 * ```
 */
export const COMMAND_STREAM_ENDPOINT: {
  readonly headers: { readonly Accept: 'text/event-stream' };
  readonly resultExtractor: ResultExtractor<
    ReadableStream<JsonServerSentEvent<CommandResult>>
  >;
} = Object.freeze({
  headers: Object.freeze({ Accept: ContentTypeValues.TEXT_EVENT_STREAM }),
  resultExtractor: CommandResultEventStreamResultExtractor,
});

/**
 * The endpoint options of a query whose answer is a server-sent event
 * stream: `Accept: text/event-stream`, and
 * {@link QueryEventStreamResultExtractor}, which errors the stream with a
 * {@link WowError} at the server's error event. The `*Stream` methods of the
 * query clients use it. Frozen, like {@link COMMAND_STREAM_ENDPOINT}.
 *
 * @example
 * ```typescript
 * import { api, autoGeneratedError, body, post } from '@ahoo-wang/fetcher-decorator';
 * import type { JsonServerSentEvent } from '@ahoo-wang/fetcher-eventstream';
 *
 * @api('cart')
 * class CartReportClient {
 *   @post('report/list', QUERY_STREAM_ENDPOINT)
 *   listStream(
 *     @body() query: FilterListQuery,
 *   ): Promise<ReadableStream<JsonServerSentEvent<{ total: number }>>> {
 *     throw autoGeneratedError(query);
 *   }
 * }
 * ```
 */
export const QUERY_STREAM_ENDPOINT: {
  readonly headers: { readonly Accept: 'text/event-stream' };
  readonly resultExtractor: ResultExtractor<
    ReadableStream<JsonServerSentEvent<unknown>>
  >;
} = Object.freeze({
  headers: Object.freeze({ Accept: ContentTypeValues.TEXT_EVENT_STREAM }),
  resultExtractor: QueryEventStreamResultExtractor,
});
