apiVersion: apps/v1
kind: Deployment
metadata:
  name: wow-example
  labels:
    app: wow-example
spec:
  replicas: 4
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: wow-example
  template:
    metadata:
      labels:
        app: wow-example
    spec:
      nodeSelector:
        test: service
      tolerations:
        - key: "test"
          value: service
          operator: "Equal"
          effect: "NoSchedule"
      containers:
        - name: wow-example
          image: registry.cn-shanghai.aliyuncs.com/ahoo/wow-example-server:2.4.2
          env:
            - name: LANG
              value: C.utf8
            - name: TZ
              value: Asia/Shanghai
            - name: JAVA_OPTS
              value: -Xms10240M  -Xmx10240M
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
          startupProbe:
            failureThreshold: 15
            httpGet:
              path: /actuator/health
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /actuator/health
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            initialDelaySeconds: 30
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /actuator/health
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            initialDelaySeconds: 30
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "16"
              memory: 12288Mi
            requests:
              cpu: '8'
              memory: 10240Mi
          volumeMounts:
            - mountPath: /etc/localtime
              name: volume-localtime
            - mountPath: /opt/example-server/config/
              name: wow-example-config
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ""
          name: volume-localtime
        - name: wow-example-config
          configMap:
            name: wow-example-config