coverage:
  range: 60..100
  round: down
  precision: 2
  status:
    patch:
      default:
        target: 60%
        threshold: 1%
    project:
      default:
        target: 80%
        threshold: 1%
ignore:
  - "document/.*"
  - "test/wow-it/.*"
  - "test/wow-tck/.*"
  - "test/wow-test/.*"
  - "wow-api/.*"
  - "wow-apiclient/.*"
  - "example/example-api/.*"
  - "example/transfer/example-transfer-api/.*"