/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type {
  EnumDeclarationStructure,
  MethodDeclarationStructure,
  OptionalKind,
  ParameterDeclarationStructure,
  TypeAliasDeclarationStructure,
  VariableStatementStructure,
} from 'ts-morph';
import { StructureKind, VariableDeclarationKind } from 'ts-morph';
import type { AggregateModel, CommandModel } from '../analysis/model';
import {
  addImport,
  addImportBoundedContext,
  addImportRefModel,
} from '../emit/imports';
import { addJSDoc } from '../emit/jsdoc';
import type { ModuleBuilder } from '../emit/moduleBuilder';
import { membersWithTrailingComma } from '../emit/moduleBuilder';
import { quoteStringLiteral } from '../naming/naming';
import { IMPORT_WOW_PATH } from '../wow/conventions';
import {
  addApiMetadataCtor,
  addImportDecorator,
  COMMAND_STREAM_ENDPOINT_METADATA,
  createDecoratorClass,
  methodToDecorator,
} from './decorators';
import type { EmitTarget } from './target';

const DEFAULT_COMMAND_CLIENT_OPTIONS = 'DEFAULT_COMMAND_CLIENT_OPTIONS';

/**
 * Writes the command client of an aggregate: the enum of its command routes,
 * a type per command body, the client, whose methods send the commands, and
 * the streaming client, which waits on their results as server-sent events.
 *
 * @param aggregate - The aggregate
 * @param target - Where it is written
 */
export function emitCommandClient(
  aggregate: AggregateModel,
  target: EmitTarget,
): void {
  const client = aggregate.commandClient;
  const module = target.modules.module(client.file);
  module.add<EnumDeclarationStructure>({
    kind: StructureKind.Enum,
    name: client.endpointPathsName,
    isExported: true,
    members: membersWithTrailingComma(
      client.commands.map(command => ({
        name: command.endpointMember,
        initializer: quoteStringLiteral(command.path),
      })),
    ),
  });
  client.commands.forEach(command =>
    addCommandType(module, target.outputDir, command),
  );
  addImportBoundedContext(
    module,
    target.outputDir,
    aggregate.context.alias,
    aggregate.context.constantName,
  );
  module.add<VariableStatementStructure>({
    kind: StructureKind.VariableStatement,
    declarationKind: VariableDeclarationKind.Const,
    declarations: [
      {
        name: DEFAULT_COMMAND_CLIENT_OPTIONS,
        type: 'ApiMetadata',
        initializer: `{
        basePath: ${aggregate.context.constantName}
      }`,
      },
    ],
    isExported: false,
  });
  addImport(module, IMPORT_WOW_PATH, [
    'CommandRequest',
    'CommandResult',
    'CommandResultEventStream',
    'CommandBody',
    COMMAND_STREAM_ENDPOINT_METADATA,
  ]);
  addImport(module, '@ahoo-wang/fetcher', ['PartialBy']);
  addImportDecorator(module);

  const commandClient = createDecoratorClass(
    client.className,
    module,
    [],
    ['R = CommandResult'],
  );
  addApiMetadataCtor(commandClient, `...${DEFAULT_COMMAND_CLIENT_OPTIONS}`);
  for (const command of client.commands) {
    const parameters = commandParameters(command);
    const method: OptionalKind<MethodDeclarationStructure> = {
      name: command.methodName,
      decorators: [
        {
          name: methodToDecorator(command.httpMethod),
          arguments: [`${client.endpointPathsName}.${command.endpointMember}`],
        },
      ],
      parameters,
      returnType: 'Promise<R>',
      statements: `throw autoGeneratedError(${parameters.map(parameter => parameter.name).join(',')});`,
    };
    (commandClient.methods ??= []).push(method);
    addJSDoc(method, [...command.docs]);
  }

  // Inherits the constructor, which merges apiMetadata over the defaults.
  // wow-client's endpoint preset errors the stream with a WowError at the
  // server's error event, as CommandClient.sendAndWaitStream does.
  createDecoratorClass(
    client.streamClassName,
    module,
    [`''`, COMMAND_STREAM_ENDPOINT_METADATA],
    [],
    `${client.className}<CommandResultEventStream>`,
  );
}

/**
 * The type of a command's body, `CommandBody<PartialBy<Body, 'optional'>>`;
 * Wow's own commands have theirs in wow-client.
 */
function addCommandType(
  module: ModuleBuilder,
  outputDir: string,
  command: CommandModel,
): void {
  if (command.body.path === IMPORT_WOW_PATH) {
    addImport(module, IMPORT_WOW_PATH, [command.typeName]);
    return;
  }
  addImportRefModel(module, outputDir, command.body);
  let commandType = command.body.name;
  const optionalFields = command.optionalFields
    .map(quoteStringLiteral)
    .join(' | ');
  if (optionalFields !== '') {
    commandType = `PartialBy<${commandType},${optionalFields}>`;
  }
  module.add<TypeAliasDeclarationStructure>({
    kind: StructureKind.TypeAlias,
    name: command.typeName,
    type: `CommandBody<${commandType}>`,
    isExported: true,
  });
}

/** The path parameters, the command request and the attributes of a method. */
function commandParameters(
  command: CommandModel,
): OptionalKind<ParameterDeclarationStructure>[] {
  return [
    ...command.pathParameters.map(parameter => ({
      name: parameter.name,
      type: parameter.type,
      hasQuestionToken: false,
      decorators: [
        { name: 'path', arguments: [quoteStringLiteral(parameter.pathName)] },
      ],
    })),
    {
      name: 'commandRequest',
      hasQuestionToken: command.requestOptional,
      type: `CommandRequest<${command.typeName}>`,
      decorators: [{ name: 'request', arguments: [] }],
    },
    {
      name: 'attributes',
      hasQuestionToken: true,
      type: 'Record<string, unknown>',
      decorators: [{ name: 'attribute', arguments: [] }],
    },
  ];
}
