import { ContentTypeValues, PartialBy } from "@ahoo-wang/fetcher";
import { type ApiMetadata, type ApiMetadataCapable, api, attribute, autoGeneratedError, del, path, post, put, request } from "@ahoo-wang/fetcher-decorator";
import { JsonEventStreamResultExtractor } from "@ahoo-wang/fetcher-eventstream";
import type { CommandBody, CommandRequest, CommandResult, CommandResultEventStream, DeleteAggregateCommand, RecoverAggregateCommand } from "@ahoo-wang/fetcher-wow";
import { ApplyExecutionFailed, ApplyExecutionSuccess, ApplyRetrySpec, ChangeFunction, CreateExecutionFailed, ForcePrepareCompensation, MarkRecoverable, PrepareCompensation } from "./types";
import { COMPENSATION_BOUNDED_CONTEXT_ALIAS } from "../boundedContext";

export enum ExecutionFailedCommandEndpointPaths {
    APPLY_EXECUTION_FAILED = '/execution_failed/{id}/apply_execution_failed',
    APPLY_EXECUTION_SUCCESS = '/execution_failed/{id}/apply_execution_success',
    APPLY_RETRY_SPEC = '/execution_failed/{id}/apply_retry_spec',
    CHANGE_FUNCTION = '/execution_failed/{id}/change_function',
    CREATE_EXECUTION_FAILED = '/execution_failed/create_execution_failed',
    DEFAULT_DELETE_AGGREGATE = '/execution_failed/{id}',
    DEFAULT_RECOVER_AGGREGATE = '/execution_failed/{id}/recover',
    FORCE_PREPARE_COMPENSATION = '/execution_failed/{id}/force_prepare_compensation',
    MARK_RECOVERABLE = '/execution_failed/{id}/mark_recoverable',
    PREPARE_COMPENSATION = '/execution_failed/{id}/prepare_compensation'
}

export type ApplyExecutionFailedCommand = CommandBody<PartialBy<ApplyExecutionFailed, 'recoverable'>>;
export type ApplyExecutionSuccessCommand = CommandBody<ApplyExecutionSuccess>;
export type ApplyRetrySpecCommand = CommandBody<ApplyRetrySpec>;
export type ChangeFunctionCommand = CommandBody<ChangeFunction>;
export type CreateExecutionFailedCommand = CommandBody<PartialBy<CreateExecutionFailed, 'recoverable' | 'retrySpec'>>;
export type ForcePrepareCompensationCommand = CommandBody<ForcePrepareCompensation>;
export type MarkRecoverableCommand = CommandBody<MarkRecoverable>;
export type PrepareCompensationCommand = CommandBody<PrepareCompensation>;

const DEFAULT_COMMAND_CLIENT_OPTIONS: ApiMetadata = {
    basePath: COMPENSATION_BOUNDED_CONTEXT_ALIAS
};

@api()
export class ExecutionFailedCommandClient<R = CommandResult> implements ApiMetadataCapable {
    constructor(public readonly apiMetadata: ApiMetadata = DEFAULT_COMMAND_CLIENT_OPTIONS) {
    }

    /**
     * apply_execution_failed
     * - operationId: `compensation.execution_failed.apply_execution_failed`
     * - path: `/execution_failed/{id}/apply_execution_failed`
     */
    @put(ExecutionFailedCommandEndpointPaths.APPLY_EXECUTION_FAILED)
    applyExecutionFailed(@path('id') id: string, @request() commandRequest: CommandRequest<ApplyExecutionFailedCommand>, @attribute() attributes?: Record<string, any>): Promise<R> {
        throw autoGeneratedError(id, commandRequest, attributes);
    }

    /**
     * apply_execution_success
     * - operationId: `compensation.execution_failed.apply_execution_success`
     * - path: `/execution_failed/{id}/apply_execution_success`
     */
    @put(ExecutionFailedCommandEndpointPaths.APPLY_EXECUTION_SUCCESS)
    applyExecutionSuccess(@path('id') id: string, @request() commandRequest: CommandRequest<ApplyExecutionSuccessCommand>, @attribute() attributes?: Record<string, any>): Promise<R> {
        throw autoGeneratedError(id, commandRequest, attributes);
    }

    /**
     * apply_retry_spec
     * - operationId: `compensation.execution_failed.apply_retry_spec`
     * - path: `/execution_failed/{id}/apply_retry_spec`
     */
    @put(ExecutionFailedCommandEndpointPaths.APPLY_RETRY_SPEC)
    applyRetrySpec(@path('id') id: string, @request() commandRequest: CommandRequest<ApplyRetrySpecCommand>, @attribute() attributes?: Record<string, any>): Promise<R> {
        throw autoGeneratedError(id, commandRequest, attributes);
    }

    /**
     * change_function
     * - operationId: `compensation.execution_failed.change_function`
     * - path: `/execution_failed/{id}/change_function`
     */
    @put(ExecutionFailedCommandEndpointPaths.CHANGE_FUNCTION)
    changeFunction(@path('id') id: string, @request() commandRequest: CommandRequest<ChangeFunctionCommand>, @attribute() attributes?: Record<string, any>): Promise<R> {
        throw autoGeneratedError(id, commandRequest, attributes);
    }

    /**
     * create_execution_failed
     * - operationId: `compensation.execution_failed.create_execution_failed`
     * - path: `/execution_failed/create_execution_failed`
     */
    @post(ExecutionFailedCommandEndpointPaths.CREATE_EXECUTION_FAILED)
    createExecutionFailed(@request() commandRequest: CommandRequest<CreateExecutionFailedCommand>, @attribute() attributes?: Record<string, any>): Promise<R> {
        throw autoGeneratedError(commandRequest, attributes);
    }

    /**
     * Delete aggregate
     * - operationId: `compensation.execution_failed.default_delete_aggregate`
     * - path: `/execution_failed/{id}`
     */
    @del(ExecutionFailedCommandEndpointPaths.DEFAULT_DELETE_AGGREGATE)
    defaultDeleteAggregate(@path('id') id: string, @request() commandRequest?: CommandRequest<DeleteAggregateCommand>, @attribute() attributes?: Record<string, any>): Promise<R> {
        throw autoGeneratedError(id, commandRequest, attributes);
    }

    /**
     * Recover deleted aggregate
     * - operationId: `compensation.execution_failed.default_recover_aggregate`
     * - path: `/execution_failed/{id}/recover`
     */
    @put(ExecutionFailedCommandEndpointPaths.DEFAULT_RECOVER_AGGREGATE)
    defaultRecoverAggregate(@path('id') id: string, @request() commandRequest?: CommandRequest<RecoverAggregateCommand>, @attribute() attributes?: Record<string, any>): Promise<R> {
        throw autoGeneratedError(id, commandRequest, attributes);
    }

    /**
     * force_prepare_compensation
     * - operationId: `compensation.execution_failed.force_prepare_compensation`
     * - path: `/execution_failed/{id}/force_prepare_compensation`
     */
    @put(ExecutionFailedCommandEndpointPaths.FORCE_PREPARE_COMPENSATION)
    forcePrepareCompensation(@path('id') id: string, @request() commandRequest?: CommandRequest<ForcePrepareCompensationCommand>, @attribute() attributes?: Record<string, any>): Promise<R> {
        throw autoGeneratedError(id, commandRequest, attributes);
    }

    /**
     * mark_recoverable
     * - operationId: `compensation.execution_failed.mark_recoverable`
     * - path: `/execution_failed/{id}/mark_recoverable`
     */
    @put(ExecutionFailedCommandEndpointPaths.MARK_RECOVERABLE)
    markRecoverable(@path('id') id: string, @request() commandRequest: CommandRequest<MarkRecoverableCommand>, @attribute() attributes?: Record<string, any>): Promise<R> {
        throw autoGeneratedError(id, commandRequest, attributes);
    }

    /**
     * prepare_compensation
     * - operationId: `compensation.execution_failed.prepare_compensation`
     * - path: `/execution_failed/{id}/prepare_compensation`
     */
    @put(ExecutionFailedCommandEndpointPaths.PREPARE_COMPENSATION)
    prepareCompensation(@path('id') id: string, @request() commandRequest?: CommandRequest<PrepareCompensationCommand>, @attribute() attributes?: Record<string, any>): Promise<R> {
        throw autoGeneratedError(id, commandRequest, attributes);
    }
}

@api('', {
    headers: { Accept: ContentTypeValues.TEXT_EVENT_STREAM },
    resultExtractor: JsonEventStreamResultExtractor,
})
export class ExecutionFailedStreamCommandClient extends ExecutionFailedCommandClient<CommandResultEventStream> {
    constructor(apiMetadata: ApiMetadata = DEFAULT_COMMAND_CLIENT_OPTIONS) {
        super(apiMetadata);
    }
}
