// Code generated by wow-generator. DO NOT EDIT.

import { QueryClientFactory, type QueryClientOptions, ResourceAttributionPathSpec } from '@ahoo-wang/wow-client';
import { COMPENSATION_BOUNDED_CONTEXT_ALIAS } from '../boundedContext.js';
import type { CompensationPrepared, ExecutionFailedAggregatedFields, ExecutionFailedApplied, ExecutionFailedCreated, ExecutionFailedState, ExecutionSuccessApplied, FunctionChanged, RecoverableMarked, RetrySpecApplied } from './types.js';

const DEFAULT_QUERY_CLIENT_OPTIONS: QueryClientOptions = {
  contextAlias: COMPENSATION_BOUNDED_CONTEXT_ALIAS,
  aggregateName: 'execution_failed',
  resourceAttribution: ResourceAttributionPathSpec.NONE,
};

export enum ExecutionFailedDomainEventTypeMapTitle {
  compensation_prepared = 'compensation_prepared',
  execution_failed_applied = 'execution_failed_applied',
  execution_failed_created = 'execution_failed_created',
  execution_success_applied = 'execution_success_applied',
  function_changed = 'function_changed',
  recoverable_marked = 'recoverable_marked',
  retry_spec_applied = 'retry_spec_applied',
}

export type ExecutionFailedDomainEventType = CompensationPrepared | ExecutionFailedApplied | ExecutionFailedCreated | ExecutionSuccessApplied | FunctionChanged | RecoverableMarked | RetrySpecApplied;

export const executionFailedQueryClientFactory = new QueryClientFactory<ExecutionFailedState, `${ExecutionFailedAggregatedFields}`, ExecutionFailedDomainEventType>(DEFAULT_QUERY_CLIENT_OPTIONS);
