/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {
  api,
  ApiMetadata,
  ApiMetadataCapable,
  attribute,
  autoGeneratedError,
  get,
  path,
} from '@ahoo-wang/fetcher-decorator';

export class LoadStateAggregateEndpointPaths {
  static readonly LOAD = '{id}/state';
  static readonly LOAD_VERSIONED = `${LoadStateAggregateEndpointPaths.LOAD}/{version}`;
  static readonly LOAD_TIME_BASED = `${LoadStateAggregateEndpointPaths.LOAD}/time/{createTime}`;
}

@api()
export class LoadStateAggregateClient<S> implements ApiMetadataCapable {
  constructor(public readonly apiMetadata?: ApiMetadata) {

  }

  @get(LoadStateAggregateEndpointPaths.LOAD)
  load(@path('id') id: string, @attribute() attributes?: Record<string, any>, abortController?: AbortController): Promise<S> {
    throw autoGeneratedError(id, attributes, abortController);
  }

  @get(LoadStateAggregateEndpointPaths.LOAD_VERSIONED)
  loadVersioned(@path('id') id: string, @path('version') version: number, @attribute() attributes?: Record<string, any>, abortController?: AbortController): Promise<S> {
    throw autoGeneratedError(id, version, attributes, abortController);
  }

  @get(LoadStateAggregateEndpointPaths.LOAD_TIME_BASED)
  loadTimeBased(@path('id') id: string, @path('createTime') createTime: number, @attribute() attributes?: Record<string, any>, abortController?: AbortController): Promise<S> {
    throw autoGeneratedError(id, createTime, attributes, abortController);
  }

}
