/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type { SnapshotQueryApi } from './snapshotQueryApi.js';
import { SnapshotQueryEndpointPaths } from './endpointPaths.js';
import type { Condition } from '../../legacy/condition.js';
import type { AggregationQuery } from '../aggregation.js';
import { filter, type FilterExpression } from '../../dsl/filter/index.js';
// compat(wow<9): the request unions admit the Condition-based queries of `/legacy`, which Wow < 8.11 needs; narrow them to the Filter* queries in v10.
import type {
  ListQueryRequest,
  PagedQueryRequest,
  SingleQueryRequest,
} from '../../legacy/queryable.js';
import { listQuery, type PagedList, singleQuery } from '../queryable.js';
import type { MaterializedSnapshot } from './snapshot.js';
import type { DynamicDocument } from '../types.js';
import type { JsonServerSentEvent } from '@ahoo-wang/fetcher-eventstream';
import type { CursorPage, CursorQuery } from '../cursorQuery.js';
import { QUERY_STREAM_ENDPOINT } from '../../eventStreams.js';
import type {
  ApiMetadata,
  ApiMetadataCapable,
} from '@ahoo-wang/fetcher-decorator';
import {
  api,
  attribute,
  autoGeneratedError,
  body,
  post,
} from '@ahoo-wang/fetcher-decorator';

/**
 * A client for querying snapshot data through HTTP endpoints.
 * Provides methods for various query operations such as counting, listing, paging, and retrieving single snapshots.
 *
 * @example
 * ```typescript
 * // Define the state interface
 * interface CartItem {
 *   productId: string;
 *   quantity: number;
 * }
 *
 * interface CartState {
 *   items: CartItem[];
 * }
 *
 * // Create client options configuration
 * const clientOptions: ApiMetadata = {
 *   fetcher: new Fetcher({ baseURL: 'http://localhost:8080/' }),
 *   basePath: 'owner/{ownerId}/cart'
 * };
 *
 * // Create a snapshot query client instance
 * const snapshotQueryClient = new SnapshotQueryClient<CartState>(clientOptions);
 *
 * // Count snapshots
 * const count = await snapshotQueryClient.count(filter.matchAll());
 *
 * // List snapshots
 * const listQuery: FilterListQuery = {
 *   filter: filter.matchAll()
 * };
 * const list = await snapshotQueryClient.list(listQuery);
 *
 * // List snapshots as stream
 * const listStream = await snapshotQueryClient.listStream(listQuery);
 * for await (const event of listStream) {
 *   const snapshot = event.data;
 *   console.log('Received:', snapshot);
 * }
 *
 * // List snapshot states
 * const stateList = await snapshotQueryClient.listState(listQuery);
 *
 * // List snapshot states as stream
 * const stateListStream = await snapshotQueryClient.listStateStream(listQuery);
 * for await (const event of stateListStream) {
 *   const state = event.data;
 *   console.log('Received state:', state);
 * }
 *
 * // Paged snapshots
 * const pagedQuery: FilterPagedQuery = {
 *   filter: filter.matchAll(),
 *   pagination: { index: 1, size: 10 }
 * };
 * const paged = await snapshotQueryClient.paged(pagedQuery);
 *
 * // Paged snapshot states
 * const pagedState = await snapshotQueryClient.pagedState(pagedQuery);
 *
 * // Single snapshot
 * const singleQuery: FilterSingleQuery = {
 *   filter: filter.matchAll()
 * };
 * const single = await snapshotQueryClient.single(singleQuery);
 *
 * // Single snapshot state
 * const singleState = await snapshotQueryClient.singleState(singleQuery);
 * ```
 *
 * @template S The type of the snapshot state
 */
@api()
export class SnapshotQueryClient<S, FIELDS extends string = string>
  implements SnapshotQueryApi<S, FIELDS>, ApiMetadataCapable
{
  /**
   * Creates a new SnapshotQueryClient instance.
   */
  constructor(public readonly apiMetadata?: ApiMetadata) {}

  /** Runs a snapshot aggregation and returns all result rows. */
  @post(SnapshotQueryEndpointPaths.AGGREGATION)
  /* v8 ignore start */
  aggregate<
    Row extends DynamicDocument = DynamicDocument,
    AGGREGATION_FIELDS extends string = string,
  >(
    @body() query: AggregationQuery<FIELDS, AGGREGATION_FIELDS>,
    @attribute() attributes?: Record<string, unknown>,
    abort?: AbortController | AbortSignal,
  ): Promise<Row[]> {
    throw autoGeneratedError(query, attributes, abort);
  }
  /* v8 ignore stop */

  /** Runs a snapshot aggregation and streams result rows as SSE. */
  @post(SnapshotQueryEndpointPaths.AGGREGATION, QUERY_STREAM_ENDPOINT)
  /* v8 ignore start */
  aggregateStream<
    Row extends DynamicDocument = DynamicDocument,
    AGGREGATION_FIELDS extends string = string,
  >(
    @body() query: AggregationQuery<FIELDS, AGGREGATION_FIELDS>,
    @attribute() attributes?: Record<string, unknown>,
    abort?: AbortController | AbortSignal,
  ): Promise<ReadableStream<JsonServerSentEvent<Row>>> {
    throw autoGeneratedError(query, attributes, abort);
  }
  /* v8 ignore stop */

  /** Retrieves the next cursor page of materialized snapshots. */
  @post(SnapshotQueryEndpointPaths.CURSOR)
  /* v8 ignore start */
  cursor<T extends Partial<MaterializedSnapshot<S>> = MaterializedSnapshot<S>>(
    @body() query: CursorQuery<FIELDS>,
    @attribute() attributes?: Record<string, unknown>,
    abort?: AbortController | AbortSignal,
  ): Promise<CursorPage<T>> {
    throw autoGeneratedError(query, attributes, abort);
  }
  /* v8 ignore stop */

  /** Retrieves the next cursor page of snapshot states. */
  @post(SnapshotQueryEndpointPaths.CURSOR_STATE)
  /* v8 ignore start */
  cursorState<T extends Partial<S> = S>(
    @body() query: CursorQuery<FIELDS>,
    @attribute() attributes?: Record<string, unknown>,
    abort?: AbortController | AbortSignal,
  ): Promise<CursorPage<T>> {
    throw autoGeneratedError(query, attributes, abort);
  }
  /* v8 ignore stop */

  /**
   * Counts the number of snapshots that match the given filter.
   *
   * @param filter - The filter expression or legacy condition
   * @param attributes - Optional shared attributes that can be accessed by interceptors
   *                     throughout the request lifecycle. These attributes allow passing
   *                     custom data between different interceptors.
   * @param abort - Cancels the request: an `AbortController`, or an `AbortSignal` such as `AbortSignal.timeout(ms)` or the `signal` a data-fetching library passes.
   * @returns A promise that resolves to the count of matching snapshots
   *
   * @example
   * ```typescript
   * const count = await snapshotQueryClient.count(filter.matchAll());
   * console.log('Total snapshots:', count);
   * ```
   */
  @post(SnapshotQueryEndpointPaths.COUNT)
  /* v8 ignore start */
  count(
    // compat(wow<9): accepts the deprecated Condition, which Wow < 8.11 needs; narrow to FilterExpression in v10.
    @body() filter: FilterExpression<FIELDS> | Condition<FIELDS>,
    @attribute() attributes?: Record<string, unknown>,
    abort?: AbortController | AbortSignal,
  ): Promise<number> {
    throw autoGeneratedError(filter, attributes, abort);
  }
  /* v8 ignore stop */

  /**
   * Retrieves a list of materialized snapshots based on the provided query parameters.
   *
   * @param listQuery - The query parameters for listing snapshots
   * @param attributes - Optional shared attributes that can be accessed by interceptors
   *                     throughout the request lifecycle. These attributes allow passing
   *                     custom data between different interceptors.
   * @param abort - Cancels the request: an `AbortController`, or an `AbortSignal` such as `AbortSignal.timeout(ms)` or the `signal` a data-fetching library passes.
   * @returns A promise that resolves to an array of partial materialized snapshots
   *
   * @example
   * ```typescript
   * const listQuery: FilterListQuery = {
   *   filter: filter.matchAll()
   * };
   * const list = await snapshotQueryClient.list(listQuery);
   * for (const snapshot of list) {
   *   console.log('Snapshot:', snapshot);
   * }
   * ```
   */
  @post(SnapshotQueryEndpointPaths.LIST)
  /* v8 ignore start */
  list<T extends Partial<MaterializedSnapshot<S>> = MaterializedSnapshot<S>>(
    @body() listQuery: ListQueryRequest<FIELDS>,
    @attribute() attributes?: Record<string, unknown>,
    abort?: AbortController | AbortSignal,
  ): Promise<T[]> {
    throw autoGeneratedError(listQuery, attributes, abort);
  }
  /* v8 ignore stop */

  /**
   * Retrieves a stream of materialized snapshots based on the provided query parameters.
   *
   * @param listQuery - The query parameters for listing snapshots
   * @param attributes - Optional shared attributes that can be accessed by interceptors
   *                     throughout the request lifecycle. These attributes allow passing
   *                     custom data between different interceptors.
   * @param abort - Cancels the request: an `AbortController`, or an `AbortSignal` such as `AbortSignal.timeout(ms)` or the `signal` a data-fetching library passes.
   * @returns A promise that resolves to a readable stream of JSON server-sent events containing partial materialized snapshots
   *
   * @example
   * ```typescript
   * const listQuery: FilterListQuery = {
   *   filter: filter.matchAll()
   * };
   * const listStream = await snapshotQueryClient.listStream(listQuery);
   * for await (const event of listStream) {
   *   const snapshot = event.data;
   *   console.log('Received snapshot:', snapshot);
   * }
   * ```
   */
  @post(SnapshotQueryEndpointPaths.LIST, QUERY_STREAM_ENDPOINT)
  /* v8 ignore start */
  listStream<
    T extends Partial<MaterializedSnapshot<S>> = MaterializedSnapshot<S>,
  >(
    @body() listQuery: ListQueryRequest<FIELDS>,
    @attribute() attributes?: Record<string, unknown>,
    abort?: AbortController | AbortSignal,
  ): Promise<ReadableStream<JsonServerSentEvent<T>>> {
    throw autoGeneratedError(listQuery, attributes, abort);
  }
  /* v8 ignore stop */

  /**
   * Retrieves a list of snapshot states based on the provided query parameters.
   *
   * @param listQuery - The query parameters for listing snapshot states
   * @param attributes - Optional shared attributes that can be accessed by interceptors
   *                     throughout the request lifecycle. These attributes allow passing
   *                     custom data between different interceptors.
   * @param abort - Cancels the request: an `AbortController`, or an `AbortSignal` such as `AbortSignal.timeout(ms)` or the `signal` a data-fetching library passes.
   * @returns A promise that resolves to an array of partial snapshot states
   *
   * @example
   * ```typescript
   * const listQuery: FilterListQuery = {
   *   filter: filter.matchAll()
   * };
   * const list = await snapshotQueryClient.listState(listQuery);
   * for (const state of list) {
   *   console.log('State:', state);
   * }
   * ```
   */
  @post(SnapshotQueryEndpointPaths.LIST_STATE)
  /* v8 ignore start */
  listState<T extends Partial<S> = S>(
    @body() listQuery: ListQueryRequest<FIELDS>,
    @attribute() attributes?: Record<string, unknown>,
    abort?: AbortController | AbortSignal,
  ): Promise<T[]> {
    throw autoGeneratedError(listQuery, attributes, abort);
  }
  /* v8 ignore stop */

  /**
   * Retrieves a stream of snapshot states based on the provided query parameters.
   *
   * @param listQuery - The query parameters for listing snapshot states
   * @param attributes - Optional shared attributes that can be accessed by interceptors
   *                     throughout the request lifecycle. These attributes allow passing
   *                     custom data between different interceptors.
   * @param abort - Cancels the request: an `AbortController`, or an `AbortSignal` such as `AbortSignal.timeout(ms)` or the `signal` a data-fetching library passes.
   * @returns A promise that resolves to a readable stream of JSON server-sent events containing partial snapshot states
   *
   * @example
   * ```typescript
   * const listQuery: FilterListQuery = {
   *   filter: filter.matchAll()
   * };
   * const listStream = await snapshotQueryClient.listStateStream(listQuery);
   * for await (const event of listStream) {
   *   const state = event.data;
   *   console.log('Received state:', state);
   * }
   * ```
   */
  @post(SnapshotQueryEndpointPaths.LIST_STATE, QUERY_STREAM_ENDPOINT)
  /* v8 ignore start */
  listStateStream<T extends Partial<S> = S>(
    @body() listQuery: ListQueryRequest<FIELDS>,
    @attribute() attributes?: Record<string, unknown>,
    abort?: AbortController | AbortSignal,
  ): Promise<ReadableStream<JsonServerSentEvent<T>>> {
    throw autoGeneratedError(listQuery, attributes, abort);
  }
  /* v8 ignore stop */

  /**
   * Retrieves a paged list of materialized snapshots based on the provided query parameters.
   *
   * @param pagedQuery - The query parameters for paging snapshots
   * @param attributes - Optional shared attributes that can be accessed by interceptors
   *                     throughout the request lifecycle. These attributes allow passing
   *                     custom data between different interceptors.
   * @param abort - Cancels the request: an `AbortController`, or an `AbortSignal` such as `AbortSignal.timeout(ms)` or the `signal` a data-fetching library passes.
   * @returns A promise that resolves to a paged list of partial materialized snapshots
   *
   * @example
   * ```typescript
   * const pagedQuery: FilterPagedQuery = {
   *   filter: filter.matchAll(),
   *   pagination: { index: 1, size: 10 }
   * };
   * const paged = await snapshotQueryClient.paged(pagedQuery);
   * console.log('Total:', paged.total);
   * for (const snapshot of paged.list) {
   *   console.log('Snapshot:', snapshot);
   * }
   * ```
   */
  @post(SnapshotQueryEndpointPaths.PAGED)
  /* v8 ignore start */
  paged<T extends Partial<MaterializedSnapshot<S>> = MaterializedSnapshot<S>>(
    @body() pagedQuery: PagedQueryRequest<FIELDS>,
    @attribute() attributes?: Record<string, unknown>,
    abort?: AbortController | AbortSignal,
  ): Promise<PagedList<T>> {
    throw autoGeneratedError(pagedQuery, attributes, abort);
  }
  /* v8 ignore stop */

  /**
   * Retrieves a paged list of snapshot states based on the provided query parameters.
   *
   * @param pagedQuery - The query parameters for paging snapshot states
   * @param attributes - Optional shared attributes that can be accessed by interceptors
   *                     throughout the request lifecycle. These attributes allow passing
   *                     custom data between different interceptors.
   * @param abort - Cancels the request: an `AbortController`, or an `AbortSignal` such as `AbortSignal.timeout(ms)` or the `signal` a data-fetching library passes.
   * @returns A promise that resolves to a paged list of partial snapshot states
   *
   * @example
   * ```typescript
   * const pagedQuery: FilterPagedQuery = {
   *   filter: filter.matchAll(),
   *   pagination: { index: 1, size: 10 }
   * };
   * const pagedState = await snapshotQueryClient.pagedState(pagedQuery);
   * for (const state of pagedState.list) {
   *   console.log('State:', state);
   * }
   * ```
   */
  @post(SnapshotQueryEndpointPaths.PAGED_STATE)
  /* v8 ignore start */
  pagedState<T extends Partial<S> = S>(
    @body() pagedQuery: PagedQueryRequest<FIELDS>,
    @attribute() attributes?: Record<string, unknown>,
    abort?: AbortController | AbortSignal,
  ): Promise<PagedList<T>> {
    throw autoGeneratedError(pagedQuery, attributes, abort);
  }
  /* v8 ignore stop */

  /**
   * Retrieves a single materialized snapshot based on the provided query parameters.
   *
   * @param singleQuery - The query parameters for retrieving a single snapshot
   * @param attributes - Optional shared attributes that can be accessed by interceptors
   *                     throughout the request lifecycle. These attributes allow passing
   *                     custom data between different interceptors.
   * @param abort - Cancels the request: an `AbortController`, or an `AbortSignal` such as `AbortSignal.timeout(ms)` or the `signal` a data-fetching library passes.
   * @returns A promise that resolves to a partial materialized snapshot
   *
   * @example
   * ```typescript
   * const singleQuery: FilterSingleQuery = {
   *   filter: filter.matchAll()
   * };
   * const single = await snapshotQueryClient.single(singleQuery);
   * console.log('Snapshot:', single);
   * ```
   */
  @post(SnapshotQueryEndpointPaths.SINGLE)
  /* v8 ignore start */
  single<T extends Partial<MaterializedSnapshot<S>> = MaterializedSnapshot<S>>(
    @body() singleQuery: SingleQueryRequest<FIELDS>,
    @attribute() attributes?: Record<string, unknown>,
    abort?: AbortController | AbortSignal,
  ): Promise<T> {
    throw autoGeneratedError(singleQuery, attributes, abort);
  }
  /* v8 ignore stop */

  /**
   * Retrieves a single snapshot state based on the provided query parameters.
   *
   * @param singleQuery - The query parameters for retrieving a single snapshot state
   * @param attributes - Optional shared attributes that can be accessed by interceptors
   *                     throughout the request lifecycle. These attributes allow passing
   *                     custom data between different interceptors.
   * @param abort - Cancels the request: an `AbortController`, or an `AbortSignal` such as `AbortSignal.timeout(ms)` or the `signal` a data-fetching library passes.
   * @returns A promise that resolves to a partial snapshot state
   *
   * @example
   * ```typescript
   * const singleQuery: FilterSingleQuery = {
   *   filter: filter.matchAll()
   * };
   * const singleState = await snapshotQueryClient.singleState(singleQuery);
   * console.log('State:', singleState);
   * ```
   */
  @post(SnapshotQueryEndpointPaths.SINGLE_STATE)
  /* v8 ignore start */
  singleState<T extends Partial<S> = S>(
    @body() singleQuery: SingleQueryRequest<FIELDS>,
    @attribute() attributes?: Record<string, unknown>,
    abort?: AbortController | AbortSignal,
  ): Promise<T> {
    throw autoGeneratedError(singleQuery, attributes, abort);
  }
  /* v8 ignore stop */

  /**
   * Retrieves a single materialized snapshot by its ID.
   *
   * @param id - The unique identifier of the snapshot to retrieve
   * @param attributes - Optional shared attributes that can be accessed by interceptors
   *                     throughout the request lifecycle. These attributes allow passing
   *                     custom data between different interceptors.
   * @param abort - Cancels the request: an `AbortController`, or an `AbortSignal` such as `AbortSignal.timeout(ms)` or the `signal` a data-fetching library passes.
   * @returns A promise that resolves to the materialized snapshot with the specified ID
   *
   * @example
   * ```typescript
   * const snapshot = await snapshotQueryClient.getById('snapshot-123');
   * console.log('Snapshot:', snapshot);
   * ```
   */
  getById(
    id: string,
    @attribute() attributes?: Record<string, unknown>,
    abort?: AbortController | AbortSignal,
  ): Promise<MaterializedSnapshot<S>> {
    const query = singleQuery<FIELDS>({ filter: filter.aggregateId(id) });
    return this.single(query, attributes, abort);
  }

  /**
   * Retrieves a single snapshot state by its ID.
   *
   * @param id - The unique identifier of the snapshot whose state to retrieve
   * @param attributes - Optional shared attributes that can be accessed by interceptors
   *                     throughout the request lifecycle. These attributes allow passing
   *                     custom data between different interceptors.
   * @param abort - Cancels the request: an `AbortController`, or an `AbortSignal` such as `AbortSignal.timeout(ms)` or the `signal` a data-fetching library passes.
   * @returns A promise that resolves to the snapshot state with the specified ID
   *
   * @example
   * ```typescript
   * const state = await snapshotQueryClient.getStateById('snapshot-123');
   * console.log('State:', state);
   * ```
   */
  getStateById(
    id: string,
    @attribute() attributes?: Record<string, unknown>,
    abort?: AbortController | AbortSignal,
  ): Promise<S> {
    const query = singleQuery<FIELDS>({ filter: filter.aggregateId(id) });
    return this.singleState(query, attributes, abort);
  }

  /**
   * Retrieves multiple materialized snapshots by their IDs.
   *
   * One request, filtered by `filter.aggregateIds(ids)` with `limit` set to
   * the number of ids; an empty `ids` sends nothing and resolves to `[]`. The
   * server refuses more ids than its filter value limit and its maximum list
   * size (1000 each by default), so split a larger set into batches.
   *
   * @param ids - An array of unique identifiers of the snapshots to retrieve
   * @param attributes - Optional shared attributes that can be accessed by interceptors
   *                     throughout the request lifecycle. These attributes allow passing
   *                     custom data between different interceptors.
   * @param abort - Cancels the request: an `AbortController`, or an `AbortSignal` such as `AbortSignal.timeout(ms)` or the `signal` a data-fetching library passes.
   * @returns A promise that resolves to an array of materialized snapshots with the specified IDs
   *
   * @example
   * ```typescript
   * const snapshots = await snapshotQueryClient.getByIds(['snapshot-123', 'snapshot-456']);
   * for (const snapshot of snapshots) {
   *   console.log('Snapshot:', snapshot);
   * }
   * ```
   */
  getByIds(
    ids: string[],
    @attribute() attributes?: Record<string, unknown>,
    abort?: AbortController | AbortSignal,
  ): Promise<MaterializedSnapshot<S>[]> {
    if (ids.length === 0) return Promise.resolve([]);
    const query = listQuery<FIELDS>({
      filter: filter.aggregateIds(ids),
      limit: ids.length,
    });
    return this.list(query, attributes, abort);
  }

  /**
   * Retrieves multiple snapshot states by their IDs.
   *
   * One request, filtered by `filter.aggregateIds(ids)` with `limit` set to
   * the number of ids; an empty `ids` sends nothing and resolves to `[]`. The
   * server refuses more ids than its filter value limit and its maximum list
   * size (1000 each by default), so split a larger set into batches.
   *
   * @param ids - An array of unique identifiers of the snapshots whose states to retrieve
   * @param attributes - Optional shared attributes that can be accessed by interceptors
   *                     throughout the request lifecycle. These attributes allow passing
   *                     custom data between different interceptors.
   * @param abort - Cancels the request: an `AbortController`, or an `AbortSignal` such as `AbortSignal.timeout(ms)` or the `signal` a data-fetching library passes.
   * @returns A promise that resolves to an array of snapshot states with the specified IDs
   *
   * @example
   * ```typescript
   * const states = await snapshotQueryClient.getStateByIds(['snapshot-123', 'snapshot-456']);
   * for (const state of states) {
   *   console.log('State:', state);
   * }
   * ```
   */
  getStateByIds(
    ids: string[],
    @attribute() attributes?: Record<string, unknown>,
    abort?: AbortController | AbortSignal,
  ): Promise<S[]> {
    if (ids.length === 0) return Promise.resolve([]);
    const query = listQuery<FIELDS>({
      filter: filter.aggregateIds(ids),
      limit: ids.length,
    });
    return this.listState(query, attributes, abort);
  }
}
