apiVersion: v1
kind: ConfigMap
metadata:
  name: wow-example-config
data:
  application.yaml: >-
    logging:
      level:
        me.ahoo.wow: warn
    
    spring:
      application:
        name: example-service
      autoconfigure:
        exclude:
          - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
      data:
        redis:
          cluster:
            max-redirects: 3
            nodes:
                - redis-test-redis-cluster-0.redis-test-redis-cluster-headless.test.svc.cluster.local:6379
          password: VPI7MsrrF7beIg
    cosid:
      machine:
        enabled: true
        distributor:
          type: redis
      generator:
        enabled: true
    wow:
      command:
        bus:
          type: kafka
      event:
        bus:
          type: kafka
      kafka:
        bootstrap-servers: 'kafka-test-0.kafka-test-headless.test.svc.cluster.local:9093'
      eventsourcing:
        store:
          storage: redis
        snapshot:
          storage: redis
        state:
          bus:
            type: kafka