/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { ContentTypeValues, type ResultExtractor } from '@ahoo-wang/fetcher';
import type { CommandResult } from '../model/command.js';
import {
  CommandResultEventStreamResultExtractor,
  QueryEventStreamResultExtractor,
} from './eventStreams.js';

/**
 * The endpoint options of a command whose answer is a server-sent event
 * stream: `Accept: text/event-stream`, and
 * {@link CommandResultEventStreamResultExtractor}, which errors the stream
 * with a {@link WowError} at the server's error event.
 * `CommandClient.sendAndWaitStream` uses it.
 *
 * A decorated command client that streams, hand-written or generated, takes
 * it whole instead of spelling out the header and the extractor, so the
 * transport is defined in one place. It fits both `@api` and the endpoint
 * decorators. It is frozen; spread it to add options.
 *
 * @example
 * ```typescript
 * import { api, autoGeneratedError, post, request } from '@ahoo-wang/fetcher-decorator';
 *
 * interface AddCartItem {
 *   productId: string;
 * }
 *
 * // Every endpoint of the class streams.
 * @api('cart', COMMAND_STREAM_ENDPOINT)
 * class CartStreamCommandClient {
 *   @post('add_cart_item')
 *   addCartItem(
 *     @request() command: CommandRequest<AddCartItem>,
 *   ): Promise<CommandResultEventStream> {
 *     throw autoGeneratedError(command);
 *   }
 * }
 *
 * // One endpoint streams.
 * @api('cart')
 * class CartCommandClient {
 *   @post('add_cart_item', COMMAND_STREAM_ENDPOINT)
 *   addCartItemStream(
 *     @request() command: CommandRequest<AddCartItem>,
 *   ): Promise<CommandResultEventStream> {
 *     throw autoGeneratedError(command);
 *   }
 * }
 * ```
 */
export const COMMAND_STREAM_ENDPOINT: {
  readonly headers: { readonly Accept: 'text/event-stream' };
  readonly resultExtractor: ResultExtractor<ReadableStream<CommandResult>>;
} = Object.freeze({
  headers: Object.freeze({ Accept: ContentTypeValues.TEXT_EVENT_STREAM }),
  resultExtractor: CommandResultEventStreamResultExtractor,
});

/**
 * The endpoint options of a query whose answer is a server-sent event
 * stream: `Accept: text/event-stream`, and
 * {@link QueryEventStreamResultExtractor}, which errors the stream with a
 * {@link WowError} at the server's error event. The `*Stream` methods of the
 * query clients use it. Frozen, like {@link COMMAND_STREAM_ENDPOINT}.
 *
 * @example
 * ```typescript
 * import { api, autoGeneratedError, body, post } from '@ahoo-wang/fetcher-decorator';
 *
 * @api('cart')
 * class CartReportClient {
 *   @post('report/list', QUERY_STREAM_ENDPOINT)
 *   listStream(
 *     @body() query: FilterListQuery,
 *   ): Promise<ReadableStream<{ total: number }>> {
 *     throw autoGeneratedError(query);
 *   }
 * }
 * ```
 */
export const QUERY_STREAM_ENDPOINT: {
  readonly headers: { readonly Accept: 'text/event-stream' };
  readonly resultExtractor: ResultExtractor<ReadableStream<unknown>>;
} = Object.freeze({
  headers: Object.freeze({ Accept: ContentTypeValues.TEXT_EVENT_STREAM }),
  resultExtractor: QueryEventStreamResultExtractor,
});
