/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package me.ahoo.wow.api.annotation

/**
 * Indicates that an element was auto-generated by a tool or code generator.
 *
 * This annotation marks code elements that should not be manually modified because
 * they are automatically generated and may be overwritten during regeneration.
 * It helps developers distinguish between handwritten and generated code.
 *
 * Common use cases:
 * - Code generated by annotation processors
 * - ORM entity classes from database schemas
 * - API client code from OpenAPI specifications
 * - Protocol buffer generated classes
 *
 * Example usage:
 * ```kotlin
 * @Generated(value = "protoc", date = "2024-01-15T10:30:00Z")
 * class UserProto {
 *     // Generated protocol buffer code - do not modify
 * }
 *
 * @Generated(value = "annotation-processor", date = "2024-01-15")
 * object UserApiClient {
 *     // Generated API client code - do not modify
 * }
 * ```
 * @param value The name of the tool or generator that created the code (e.g., "protoc", "openapi-generator").
 * @param date The generation timestamp in ISO format or other readable format.
 */
annotation class Generated(
    val value: String = "",
    val date: String = ""
)
