/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Internal: the index of this folder does not re-export this file.

import {
  ExchangeResultExtractor,
  type FetchExchange,
  HttpStatusValidationError,
  IGNORE_VALIDATE_STATUS,
} from '@ahoo-wang/fetcher';
import type {
  ApiMetadata,
  ApiMetadataCapable,
} from '@ahoo-wang/fetcher-decorator';
import {
  api,
  attribute,
  autoGeneratedError,
  get,
  header,
} from '@ahoo-wang/fetcher-decorator';
import type { QueryModelDescriptor } from '../../../dsl/descriptor.js';
import type { QueryDescriptorResult } from './queryDescriptorApi.js';
import { QueryDescriptorEndpointPaths } from './endpointPaths.js';

/**
 * The endpoints answer the exchange with its status unchecked, so a 304 is
 * not an error; {@link readDescriptor} checks the status instead.
 */
const DESCRIPTOR_ENDPOINT = Object.freeze({
  resultExtractor: ExchangeResultExtractor,
  attributes: Object.freeze({ [IGNORE_VALIDATE_STATUS]: true }),
});

/**
 * The decorated requests behind `QueryDescriptorClient`, which turns the
 * version it is given into an ETag before they run.
 */
@api()
export class QueryDescriptorEndpoints implements ApiMetadataCapable {
  constructor(public readonly apiMetadata?: ApiMetadata) {}

  @get(QueryDescriptorEndpointPaths.SNAPSHOT, DESCRIPTOR_ENDPOINT)
  /* v8 ignore start */
  snapshot(
    @header('If-None-Match') ifNoneMatch?: string,
    @attribute() attributes?: Record<string, unknown>,
    abort?: AbortController | AbortSignal,
  ): Promise<FetchExchange> {
    throw autoGeneratedError(ifNoneMatch, attributes, abort);
  }
  /* v8 ignore stop */

  @get(QueryDescriptorEndpointPaths.EVENT_STREAM, DESCRIPTOR_ENDPOINT)
  /* v8 ignore start */
  eventStream(
    @header('If-None-Match') ifNoneMatch?: string,
    @attribute() attributes?: Record<string, unknown>,
    abort?: AbortController | AbortSignal,
  ): Promise<FetchExchange> {
    throw autoGeneratedError(ifNoneMatch, attributes, abort);
  }
  /* v8 ignore stop */
}

/**
 * The version a descriptor version or an ETag names: `sha256:…`,
 * `"sha256:…"` and `W/"sha256:…"` all name `sha256:…`. `undefined` for
 * nothing, or only blanks.
 */
export function descriptorVersion(previous?: string): string | undefined {
  const version = previous
    ?.trim()
    .replace(/^W\//, '')
    .replace(/^"(.*)"$/, '$1');
  return version ? version : undefined;
}

/**
 * The `If-None-Match` value for `version`: the ETag the server sends, which it
 * compares as it is.
 */
export function ifNoneMatch(version?: string): string | undefined {
  return version === undefined ? undefined : `"${version}"`;
}

/**
 * What an exchange answers: 304 means the version sent is current; any other
 * status outside 2xx rejects with the error the fetcher would have thrown.
 */
export async function readDescriptor(
  exchange: FetchExchange,
  version: string | undefined,
): Promise<QueryDescriptorResult> {
  const response = exchange.requiredResponse;
  if (response.status === 304 && version !== undefined)
    return { notModified: true, version };
  if (!response.ok) throw new HttpStatusValidationError(exchange);
  const descriptor = (await response.json()) as QueryModelDescriptor;
  return { notModified: false, descriptor, version: descriptor.version };
}
