/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { type CommandRequest } from './commandRequest';
import {
  type CommandResult,
  type CommandResultEventStream,
} from './commandResult';
import {
  ContentTypeValues,
} from '@ahoo-wang/fetcher';
import { JsonEventStreamResultExtractor } from '@ahoo-wang/fetcher-eventstream';

import {
  api,
  ApiMetadata,
  ApiMetadataCapable,
  attribute,
  autoGeneratedError,
  endpoint,
  request,
} from '@ahoo-wang/fetcher-decorator';

/**
 * Command Client for sending commands to the server.
 *
 * The CommandClient is responsible for sending commands to the server and handling the responses.
 * It provides methods for both regular command execution and streaming command results.
 *
 * @example
 * ```typescript
 * // Create a client options configuration
 * const clientOptions: ClientOptions = {
 *   fetcher: new Fetcher({ baseURL: 'http://localhost:8080/' }),
 *   basePath: 'owner/{ownerId}/cart'
 * };
 *
 * // Create a command client instance
 * const commandClient = new CommandClient(clientOptions);
 *
 * // Define command endpoint
 * const addCartItem = 'add_cart_item';
 *
 * // Create a command request
 * const addCartItemCommand: CommandRequest<AddCartItem> = {
 *   method: HttpMethod.POST,
 *   headers: {
 *     [CommandHttpHeaders.WAIT_STAGE]: CommandStage.SNAPSHOT,
 *   },
 *   body: {
 *     productId: 'productId',
 *     quantity: 1,
 *   }
 * };
 *
 * // Send command and get result
 * const commandResult = await commandClient.send(addCartItem, addCartItemCommand);
 *
 * // Send command and get result as stream
 * const commandResultStream = await commandClient.sendAndWaitStream(addCartItem, addCartItemCommand);
 * for await (const commandResultEvent of commandResultStream) {
 *   console.log('Received:', commandResultEvent.data);
 * }
 * ```
 */
@api()
export class CommandClient implements ApiMetadataCapable {
  constructor(public readonly apiMetadata?: ApiMetadata) {
  }

  /**
   * Send a command to the server and wait for the result.
   *
   * @param commandRequest - The command request to send
   * @param attributes - Optional shared attributes that can be accessed by interceptors
   *                     throughout the request lifecycle. These attributes allow passing
   *                     custom data between different interceptors.
   * @returns A promise that resolves to the command execution result
   *
   * @example
   * ```typescript
   * const commandResult = await commandClient.send('add_cart_item', {
   *   method: HttpMethod.POST,
   *   body: {
   *     productId: 'product-1',
   *     quantity: 2
   *   }
   * });
   * ```
   */
  @endpoint()
  send<C extends object = object>(
    @request() commandRequest: CommandRequest<C>,
    @attribute() attributes?: Record<string, any>,
  ): Promise<CommandResult> {
    throw autoGeneratedError(commandRequest, attributes);
  }

  /**
   * Send a command to the server and wait for the result as a stream.
   * This is useful for long-running commands that produce multiple events.
   *
   * @param commandRequest - The command request to send
   * @param attributes - Optional shared attributes that can be accessed by interceptors
   *                     throughout the request lifecycle. These attributes allow passing
   *                     custom data between different interceptors.
   * @returns A promise that resolves to a stream of command execution results
   *
   * @example
   * ```typescript
   * const commandResultStream = await commandClient.sendAndWaitStream('add_cart_item', {
   *   method: HttpMethod.POST,
   *   headers: {
   *     Accept: ContentTypeValues.TEXT_EVENT_STREAM
   *   },
   *   body: {
   *     productId: 'product-1',
   *     quantity: 2
   *   }
   * });
   *
   * for await (const commandResultEvent of commandResultStream) {
   *   console.log('Received event:', commandResultEvent.data);
   * }
   * ```
   */
  @endpoint(undefined, undefined, {
    headers: { Accept: ContentTypeValues.TEXT_EVENT_STREAM },
    resultExtractor: JsonEventStreamResultExtractor,
  })
  sendAndWaitStream<C extends object = object>(
    @request() commandRequest: CommandRequest<C>,
    @attribute() attributes?: Record<string, any>,
  ): Promise<CommandResultEventStream> {
    throw autoGeneratedError(commandRequest, attributes);
  }
}
