/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { type CommandRequest } from './commandRequest.js';
import {
  type CommandResult,
  type CommandResultEventStream,
} from './commandResult.js';
import { COMMAND_STREAM_ENDPOINT } from '../eventStreams.js';

import type {
  ApiMetadata,
  ApiMetadataCapable,
} from '@ahoo-wang/fetcher-decorator';
import {
  api,
  attribute,
  autoGeneratedError,
  endpoint,
  request,
} from '@ahoo-wang/fetcher-decorator';

/**
 * Sends commands to a Wow command route.
 *
 * The request's `path` names the command route, relative to the client's base
 * path; its `headers` say who the command is for and what to wait for (see
 * {@link commandHeaders} and {@link waitStrategy}); its `body` is the command.
 * The body type is chosen per call, so one client sends every command of an
 * aggregate.
 *
 * @example
 * ```typescript
 * const commandClient = new CommandClient({
 *   fetcher: new Fetcher({ baseURL: 'http://localhost:8080/' }),
 *   basePath: 'owner/{ownerId}/cart',
 * });
 *
 * const result = await commandClient.send<{ productId: string; quantity: number }>({
 *   path: 'add_cart_item',
 *   method: 'POST',
 *   urlParams: { path: { ownerId: 'user-1' } },
 *   headers: waitStrategy({ stage: CommandStage.SNAPSHOT }),
 *   body: { productId: 'product-1', quantity: 1 },
 * });
 * ```
 */
@api()
export class CommandClient implements ApiMetadataCapable {
  constructor(public readonly apiMetadata?: ApiMetadata) {}

  /**
   * Sends a command and resolves to the result of the stage it waited for
   * (`PROCESSED` unless the headers say otherwise). A command the server
   * refuses or fails to process rejects: Wow answers the failed result with
   * the HTTP status its `errorCode` maps to. Read it with `toWowError`.
   *
   * @param commandRequest - The route path, headers and body of the command
   * @param attributes - Optional shared attributes for the interceptors
   * @returns The command result
   */
  @endpoint()
  /* v8 ignore start */
  send<C extends object = object>(
    @request() commandRequest: CommandRequest<C>,
    @attribute() attributes?: Record<string, unknown>,
  ): Promise<CommandResult> {
    throw autoGeneratedError(commandRequest, attributes);
  }
  /* v8 ignore stop */

  /**
   * Sends a command and streams one result for every stage it reaches, up to
   * the one it waits for. The stream errors with a `WowError` if the server
   * fails midway, for example when the wait times out.
   *
   * @param commandRequest - The route path, headers and body of the command
   * @param attributes - Optional shared attributes for the interceptors
   * @returns A stream of command results
   *
   * @example
   * ```typescript
   * const results = await commandClient.sendAndWaitStream({
   *   path: 'add_cart_item',
   *   method: 'POST',
   *   headers: waitStrategy({ stage: CommandStage.PROJECTED }),
   *   body: { productId: 'product-1', quantity: 2 },
   * });
   * for await (const event of results) {
   *   console.log(event.data.stage);
   * }
   * ```
   */
  @endpoint(undefined, undefined, COMMAND_STREAM_ENDPOINT)
  /* v8 ignore start */
  sendAndWaitStream<C extends object = object>(
    @request() commandRequest: CommandRequest<C>,
    @attribute() attributes?: Record<string, unknown>,
  ): Promise<CommandResultEventStream> {
    throw autoGeneratedError(commandRequest, attributes);
  }
  /* v8 ignore stop */
}
