/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { BaseCodeGenerator } from '@/BaseCodeGenerator.ts';
import { GenerateContext } from '@/types.ts';
import { AggregateDefinition, CommandDefinition } from '@/aggregate';
import { IMPORT_WOW_PATH, resolveModelInfo } from '@/model';
import { addImport, addImportRefModel, camelCase } from '@/utils';
import { ClassDeclaration, Scope, SourceFile } from 'ts-morph';
import { HTTPMethod } from '@ahoo-wang/fetcher-openapi';
import { createClientFilePath, getClientName } from '@/client/utils.ts';

export class CommandClientGenerator extends BaseCodeGenerator {
  private readonly commandEndpointPathsName = 'COMMAND_ENDPOINT_PATHS';

  constructor(context: GenerateContext) {
    super(context);
  }

  generate(): void {
    for (const [_, aggregates] of this.contextAggregates) {
      aggregates.forEach(aggregateDefinition => {
        this.processAggregate(aggregateDefinition);
      });
    }
  }

  /**
   * Processes and generates command client for an aggregate.
   * @param aggregate - The aggregate definition
   */
  processAggregate(aggregate: AggregateDefinition) {
    const commandClientFile = createClientFilePath(
      this.project,
      this.outputDir,
      aggregate.aggregate,
      'commandClient',
    );
    this.processCommandEndpointPaths(commandClientFile, aggregate);
    commandClientFile.addImportDeclaration({
      moduleSpecifier: IMPORT_WOW_PATH,
      namedImports: [
        'CommandRequest',
        'CommandResult',
        'CommandResultEventStream',
        'DeleteAggregate',
        'RecoverAggregate',
      ],
      isTypeOnly: true,
    });
    addImport(commandClientFile, '@ahoo-wang/fetcher-decorator', [
      'type ApiMetadata',
      'type ApiMetadataCapable',
      'api',
      'post',
      'put',
      'del',
      'request',
      'attribute',
      'path',
      'autoGeneratedError',
    ]);

    this.processCommandClient(commandClientFile, aggregate);
  }

  processCommandEndpointPaths(clientFile: SourceFile, aggregateDefinition: AggregateDefinition) {
    const enumDeclaration = clientFile.addEnum({
      name: this.commandEndpointPathsName,
    });
    aggregateDefinition.commands.forEach(command => {
      enumDeclaration.addMember({
        name: command.name.toUpperCase(),
        initializer: `'${command.path}'`,
      });
    });
  }

  getEndpointPath(command: CommandDefinition): string {
    return `${this.commandEndpointPathsName}.${command.name.toUpperCase()}`;
  }

  processCommandClient(clientFile: SourceFile, aggregateDefinition: AggregateDefinition) {
    const commandClientName = getClientName(
      aggregateDefinition.aggregate,
      'CommandClient',
    );
    const commandClient = clientFile.addClass({
      name: commandClientName,
      isExported: true,
      decorators: [
        {
          name: 'api',
          arguments: [],
        },
      ],
      implements: ['ApiMetadataCapable'],
    });
    commandClient.addConstructor({
      parameters: [
        {
          name: 'apiMetadata',
          type: 'ApiMetadata',
          scope: Scope.Public,
          isReadonly: true,
        },
      ],
    });
    aggregateDefinition.commands.forEach(command => {
      this.processCommandMethod(clientFile, commandClient, command);
    });
  }

  private methodToDecorator(method: HTTPMethod): string {
    if (method === 'delete') {
      return 'del';
    }
    return method;
  }

  /**
   * Processes and generates a command method for the command client.
   * @param sourceFile - The source file containing the client
   * @param client - The client class declaration
   * @param definition - The command definition
   */
  processCommandMethod(
    sourceFile: SourceFile,
    client: ClassDeclaration,
    definition: CommandDefinition,
  ) {
    const commandModelInfo = resolveModelInfo(definition.schema.key);
    addImportRefModel(sourceFile, this.outputDir, commandModelInfo);
    const parameters = definition.pathParameters.map(parameter => {
      return {
        name: parameter.name,
        type: 'string',
        decorators: [
          {
            name: 'path',
            arguments: [`'${parameter.name}'`],
          },
        ],
      };
    });
    parameters.push({
      name: 'commandRequest',
      type: `CommandRequest<${commandModelInfo.name}>`,
      decorators: [
        {
          name: 'request',
          arguments: [],
        },
      ],
    });
    parameters.push({
      name: 'attributes',
      type: 'Record<string, any>',
      decorators: [
        {
          name: 'attribute',
          arguments: [],
        },
      ],
    });
    client.addMethod({
      name: camelCase(definition.name),
      decorators: [
        {
          name: this.methodToDecorator(definition.method),
          arguments: [`${this.getEndpointPath(definition)}`],
        },
      ],
      parameters: parameters,
      returnType: 'Promise<CommandResult>',
      statements: [
        `throw autoGeneratedError(${parameters.map(parameter => parameter.name).join(',')});`,
      ],
    });
  }
}