/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type { ClassDeclarationStructure } from 'ts-morph';
import { Scope, StructureKind } from 'ts-morph';
import { addImport } from '../emit/imports';
import type { ModuleBuilder } from '../emit/moduleBuilder';

export const FETCHER_MODULE_SPECIFIER = '@ahoo-wang/fetcher';
export const FETCHER_NAMED_IMPORTS = ['ContentTypeValues', 'ResultExtractors'];

/**
 * The module specifier for the fetcher-decorator package.
 */
export const DECORATOR_MODULE_SPECIFIER = '@ahoo-wang/fetcher-decorator';

/**
 * Named imports from the fetcher-decorator package.
 */
export const DECORATOR_NAMED_IMPORTS = [
  'ApiMetadata',
  'ApiMetadataCapable',
  'ParameterRequest',
  'api',
  'get',
  'post',
  'put',
  'patch',
  'del',
  'request',
  'attribute',
  'path',
  'query',
  'header',
  'body',
  'autoGeneratedError',
];

export interface MethodReturnType {
  type: string;
  metadata?: string;
}

export const DEFAULT_RETURN_TYPE: MethodReturnType = {
  type: 'Promise<Response>',
  metadata: `{resultExtractor: ResultExtractors.Response }`,
};

export const STRING_RETURN_TYPE: MethodReturnType = {
  type: 'Promise<string>',
  metadata: `{resultExtractor: ResultExtractors.Text }`,
};

/**
 * Metadata configuration for stream result extraction.
 */
export const STREAM_RESULT_EXTRACTOR_METADATA = `{
  headers: { Accept: ContentTypeValues.TEXT_EVENT_STREAM },
  resultExtractor: JsonEventStreamResultExtractor,
}`;

/**
 * The endpoint options of a streaming command client, imported from
 * `@ahoo-wang/wow-client`: `Accept: text/event-stream` and
 * `CommandResultEventStreamResultExtractor`, which errors the stream with a
 * `WowError` when the server sends an error event instead of passing the
 * event on as a result.
 */
export const COMMAND_STREAM_ENDPOINT_METADATA = 'COMMAND_STREAM_ENDPOINT';

export function addImportFetcher(module: ModuleBuilder) {
  addImport(module, FETCHER_MODULE_SPECIFIER, FETCHER_NAMED_IMPORTS);
}
/**
 * Adds the necessary imports for decorator functionality to a module.
 *
 * @param module - The module to add imports to
 */
export function addImportDecorator(module: ModuleBuilder) {
  addImport(module, DECORATOR_MODULE_SPECIFIER, DECORATOR_NAMED_IMPORTS);
}

/**
 * Adds a class declaration with the @api decorator to a module.
 *
 * @param className - The name of the class to create
 * @param module - The module to add the class to
 * @param apiArgs - Optional arguments for the @api decorator
 * @param typeParameters - Optional type parameters for the class
 * @param extendsClass - Optional class to extend
 * @returns The class declaration, open to members until the module is built
 *
 * @example
 * ```typescript
 * const classDecl = createDecoratorClass('UserApi', module, ['baseUrl']);
 * ```
 */
export function createDecoratorClass(
  className: string,
  module: ModuleBuilder,
  apiArgs: string[] = [],
  typeParameters: string[] = [],
  extendsClass?: string,
): ClassDeclarationStructure {
  return module.add<ClassDeclarationStructure>({
    kind: StructureKind.Class,
    name: className,
    isExported: true,
    typeParameters: typeParameters,
    extends: extendsClass,
    decorators: [
      {
        name: 'api',
        arguments: apiArgs,
      },
    ],
  });
}

/**
 * Adds the ApiMetadataCapable interface implementation and constructor to a class declaration.
 *
 * With defaults, the constructor merges what the caller passes over them, so
 * `new CartCommandClient({ fetcher })` keeps the bounded context's base path:
 *
 * ```typescript
 * readonly apiMetadata: ApiMetadata;
 * constructor(apiMetadata?: ApiMetadata) {
 *   this.apiMetadata = { ...DEFAULT_COMMAND_CLIENT_OPTIONS, ...apiMetadata };
 * }
 * ```
 *
 * @param classDeclaration - The class declaration to modify
 * @param defaults - Object literal entries the constructor starts from, such
 * as `...DEFAULT_COMMAND_CLIENT_OPTIONS` or `basePath: X`; none by default
 */
export function addApiMetadataCtor(
  classDeclaration: ClassDeclarationStructure,
  defaults?: string,
) {
  classDeclaration.implements = [
    ...[classDeclaration.implements ?? []].flat(),
    'ApiMetadataCapable',
  ];
  classDeclaration.ctors ??= [];
  if (defaults === undefined) {
    classDeclaration.ctors.push({
      parameters: [
        {
          name: 'apiMetadata',
          type: 'ApiMetadata',
          hasQuestionToken: true,
          scope: Scope.Public,
          isReadonly: true,
        },
      ],
    });
    return;
  }
  classDeclaration.properties = [
    ...(classDeclaration.properties ?? []),
    {
      name: 'apiMetadata',
      type: 'ApiMetadata',
      isReadonly: true,
    },
  ];
  classDeclaration.ctors.push({
    parameters: [
      {
        name: 'apiMetadata',
        type: 'ApiMetadata',
        hasQuestionToken: true,
      },
    ],
    statements: `this.apiMetadata = { ${defaults}, ...apiMetadata };`,
    docs: [
      '@param apiMetadata - Merged over the defaults, so passing only a `fetcher` keeps the base path.',
    ],
  });
}

export const EVENTSTREAM_MODULE_SPECIFIER = '@ahoo-wang/fetcher-eventstream';

export function addImportEventStream(module: ModuleBuilder) {
  addImport(module, EVENTSTREAM_MODULE_SPECIFIER, [
    'JsonEventStreamResultExtractor',
    'JsonServerSentEventStream',
  ]);
}
