/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { NamedFetcher } from "@ahoo-wang/fetcher";
import {
  api,
  autoGeneratedError,
  body,
  post,
} from "@ahoo-wang/fetcher-decorator";

export const compensationFetcherName = "compensation";
new NamedFetcher(compensationFetcherName, {
  baseURL: "http://compensation-service.dev.svc.cluster.local/",
});

@api("execution_failed", { fetcher: compensationFetcherName })
export class ExecutionFailedService {
  @post("snapshot/list", {
    headers: {
      Accept: "text/event-stream",
    },
  })
  async listSnapshot(@body() listQuery: Record<string, any>): Promise<Response> {
    throw autoGeneratedError();
  }
}

export const executionFailedService = new ExecutionFailedService();
