/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { ContentTypeValues, NamedFetcher } from "@ahoo-wang/fetcher";
import {
  api,
  autoGeneratedError,
  body,
  post,
} from "@ahoo-wang/fetcher-decorator";
import type {
  CommandResultEventStream,
  ListQuery,
} from "@ahoo-wang/fetcher-wow";
import {
  EventStreamInterceptor,
  type ServerSentEventStream,
} from "@ahoo-wang/fetcher-eventstream";
import { ResultExtractors } from "@ahoo-wang/fetcher-decorator";

export const COMPENSATION_FETCHER_NAME = "compensation";
const compensationFetcher = new NamedFetcher(COMPENSATION_FETCHER_NAME, {
  baseURL: "http://compensation-service.dev.svc.cluster.local/",
});
compensationFetcher.interceptors.response.use(new EventStreamInterceptor());

@api("execution_failed", {
  fetcher: compensationFetcher,
  resultExtractor: ResultExtractors.Json,
})
export class ExecutionFailedService {
  @post("snapshot/list", {
    headers: {
      Accept: ContentTypeValues.TEXT_EVENT_STREAM,
    },
    resultExtractor: ResultExtractors.JsonEventStream,
  })
  async listSnapshot(
    @body() listQuery: ListQuery,
  ): Promise<ServerSentEventStream> {
    throw autoGeneratedError(listQuery);
  }
}

@api("execution_failed", { fetcher: compensationFetcher })
export class StateExecutionFailedService extends ExecutionFailedService {
  @post("list/state", {
    headers: {
      Accept: ContentTypeValues.TEXT_EVENT_STREAM,
    },
    resultExtractor: ResultExtractors.JsonEventStream,
  })
  async listState(
    @body() listQuery: ListQuery,
  ): Promise<CommandResultEventStream> {
    throw autoGeneratedError(listQuery);
  }
}

export const executionFailedService = new ExecutionFailedService();
export const stateExecutionFailedService = new StateExecutionFailedService();
