/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { NamedFetcher } from "@ahoo-wang/fetcher";
import {
  api,
  autoGeneratedError,
  body,
  post,
} from "@ahoo-wang/fetcher-decorator";
import type { ListQuery } from "@ahoo-wang/fetcher-wow";
import { EventStreamInterceptor } from "@ahoo-wang/fetcher-eventstream";

export const COMPENSATION_FETCHER_NAME = "compensation";
const compensationFetcher = new NamedFetcher(COMPENSATION_FETCHER_NAME, {
  baseURL: "http://compensation-service.dev.svc.cluster.local/",
});
compensationFetcher.interceptors.response.use(new EventStreamInterceptor());

@api("execution_failed", { fetcher: COMPENSATION_FETCHER_NAME })
export class ExecutionFailedService {
  @post("snapshot/list", {
    headers: {
      Accept: "text/event-stream",
    },
  })
  async listSnapshot(@body() listQuery: ListQuery): Promise<Response> {
    console.log("listQuery:", listQuery); // 使用listQuery参数避免TS6133错误
    throw autoGeneratedError();
  }
}

@api("execution_failed", { fetcher: COMPENSATION_FETCHER_NAME })
export class StateExecutionFailedService extends ExecutionFailedService {
  @post("list/state", {
    headers: {
      Accept: "text/event-stream",
    },
  })
  async listState(@body() listQuery: ListQuery): Promise<Response> {
    console.log("listQuery:", listQuery);
    throw autoGeneratedError();
  }
}

export const executionFailedService = new ExecutionFailedService();
export const stateExecutionFailedService = new StateExecutionFailedService();
