/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * The stream endpoint presets are frozen objects that every streaming client
 * shares, so nothing on the request path may write to them: not the header
 * merge of the decorators or the Fetcher, not the interceptors that add a
 * header, not the exchange that holds the `resultExtractor`. A write to a
 * frozen object throws in a module, so each case here would fail loudly; the
 * cases also check that the headers of one request never reach the next.
 *
 * Runs against the fetcher packages the workspace installs (5.1.x, the lower
 * bound of the peer range).
 */

import { Fetcher, HttpMethod } from '@ahoo-wang/fetcher';
import {
  api,
  autoGeneratedError,
  post,
  request,
} from '@ahoo-wang/fetcher-decorator';
import { describe, expect, it } from 'vitest';
import {
  COMMAND_STREAM_ENDPOINT,
  CommandClient,
  CommandResultEventStreamResultExtractor,
  CommandStage,
  QUERY_STREAM_ENDPOINT,
  QueryEventStreamResultExtractor,
  SnapshotQueryClient,
  filter,
  listQuery,
  type CommandRequest,
  type CommandResultEventStream,
} from '../../src';
import {
  BASE_URL,
  readAll,
  sseResponse,
  stubFetch,
  type SentRequest,
} from './fetchStub';

function expectPresetsUnchanged() {
  expect(COMMAND_STREAM_ENDPOINT).toStrictEqual({
    headers: { Accept: 'text/event-stream' },
    resultExtractor: CommandResultEventStreamResultExtractor,
  });
  expect(QUERY_STREAM_ENDPOINT).toStrictEqual({
    headers: { Accept: 'text/event-stream' },
    resultExtractor: QueryEventStreamResultExtractor,
  });
  for (const preset of [COMMAND_STREAM_ENDPOINT, QUERY_STREAM_ENDPOINT]) {
    expect(Object.isFrozen(preset)).toBe(true);
    expect(Object.isFrozen(preset.headers)).toBe(true);
  }
}

/**
 * A real Fetcher whose request interceptor writes a header on every request,
 * after checking that the headers it writes to are the request's own copy and
 * not a preset's object.
 */
function interceptedFetcher(): Fetcher {
  const fetcher = new Fetcher({ baseURL: BASE_URL });
  let count = 0;
  fetcher.interceptors.request.use({
    name: 'StampRequest',
    order: 0,
    intercept(exchange) {
      const headers = exchange.ensureRequestHeaders();
      expect(headers).not.toBe(COMMAND_STREAM_ENDPOINT.headers);
      expect(headers).not.toBe(QUERY_STREAM_ENDPOINT.headers);
      expect(Object.isFrozen(headers)).toBe(false);
      headers['X-Request-Count'] = String(++count);
    },
  });
  return fetcher;
}

const STAGE_STREAM = `event:${CommandStage.SENT}\ndata:${JSON.stringify({ stage: CommandStage.SENT })}\n\n`;
const ROW_STREAM = `data:${JSON.stringify({ row: 1 })}\n\n`;

function headersOf(sent: SentRequest): Record<string, string> {
  return Object.fromEntries(sent.headers.entries());
}

const command = (
  headers: CommandRequest['headers'],
): CommandRequest<{ quantity: number }> => ({
  path: 'add_cart_item',
  method: HttpMethod.POST,
  headers,
  body: { quantity: 1 },
});

/**
 * A stream command client shaped like the generated ones:
 * `@api('cart', COMMAND_STREAM_ENDPOINT)` on the class, `@post` and
 * `@request()` on the method. The test transform does not parse parameter
 * decorators, so they are applied by hand in the order TypeScript applies
 * them.
 */
class CartStreamCommandClient {
  constructor(readonly apiMetadata: { fetcher: Fetcher }) {}

  addCartItem(
    commandRequest: CommandRequest<{ quantity: number }>,
  ): Promise<CommandResultEventStream> {
    throw autoGeneratedError(commandRequest);
  }
}
request()(CartStreamCommandClient.prototype, 'addCartItem', 0);
post('add_cart_item')(CartStreamCommandClient.prototype, 'addCartItem');
api('cart', COMMAND_STREAM_ENDPOINT)(CartStreamCommandClient);

describe('the stream endpoint presets on the request path', () => {
  it('stay unchanged across two command streams, the second with extra headers', async () => {
    const { requests } = stubFetch(() => sseResponse(STAGE_STREAM));
    const client = new CommandClient({
      basePath: 'cart',
      fetcher: interceptedFetcher(),
    });

    await readAll(await client.sendAndWaitStream(command({})));
    await readAll(
      await client.sendAndWaitStream(
        command({ 'Command-Request-Id': 'r-2', 'X-Extra': 'second' }),
      ),
    );

    expectPresetsUnchanged();
    const [first, second] = requests.map(headersOf);
    expect(first).toStrictEqual({
      accept: 'text/event-stream',
      'content-type': 'application/json',
      'x-request-count': '1',
    });
    expect(second).toStrictEqual({
      accept: 'text/event-stream',
      'command-request-id': 'r-2',
      'content-type': 'application/json',
      'x-extra': 'second',
      'x-request-count': '2',
    });
  });

  it('stay unchanged when a class takes one through @api, as generated code does', async () => {
    const { requests } = stubFetch(() => sseResponse(STAGE_STREAM));
    const client = new CartStreamCommandClient({
      fetcher: interceptedFetcher(),
    });

    const results = await readAll(await client.addCartItem(command({})));
    await readAll(
      await client.addCartItem(command({ 'X-Extra': 'second', Accept: '*/*' })),
    );

    expectPresetsUnchanged();
    expect(results.map(event => event.data.stage)).toEqual([CommandStage.SENT]);
    const [first, second] = requests.map(headersOf);
    expect(first).not.toHaveProperty('x-extra');
    expect(first.accept).toBe('text/event-stream');
    expect(second['x-extra']).toBe('second');
    // A request's own header wins over the preset, for that request only.
    expect(second.accept).toBe('*/*');
  });

  it('stay unchanged across two query streams from clients with different headers', async () => {
    const { requests } = stubFetch(() => sseResponse(ROW_STREAM));
    const fetcher = interceptedFetcher();
    const plain = new SnapshotQueryClient({ basePath: 'cart', fetcher });
    const spaced = new SnapshotQueryClient({
      basePath: 'cart',
      fetcher,
      headers: { 'Wow-Space-Id': 'space-2' },
    });
    const query = listQuery({ filter: filter.matchAll() });

    await readAll(await plain.listStream(query));
    await readAll(await spaced.listStream(query));
    await readAll(await plain.listStateStream(query));

    expectPresetsUnchanged();
    const [first, second, third] = requests.map(headersOf);
    expect(first).not.toHaveProperty('wow-space-id');
    expect(second['wow-space-id']).toBe('space-2');
    expect(third).not.toHaveProperty('wow-space-id');
    expect(requests.map(sent => sent.headers.get('Accept'))).toEqual([
      'text/event-stream',
      'text/event-stream',
      'text/event-stream',
    ]);
  });
});
