/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type { EventStreamQueryApi } from './eventStreamQueryApi.js';
import { EventStreamQueryEndpointPaths } from './endpointPaths.js';
import type { AggregationQuery } from '../../../dsl/aggregation/index.js';
import type { FilterExpression } from '../../../dsl/filter/index.js';
import type {
  Condition,
  ListQueryRequest,
  PagedQueryRequest,
} from '../requests.js';
import type { PagedList } from '../../../dsl/queryable.js';
import type { DomainEventStream } from './domainEventStream.js';
import type { DynamicDocument } from '../../../dsl/documents.js';
import type { JsonServerSentEvent } from '@ahoo-wang/fetcher-eventstream';
import { QUERY_STREAM_ENDPOINT } from '../../../transport/endpoints.js';
import type { CursorPage, CursorQuery } from '../../../dsl/cursorQuery.js';

import type {
  ApiMetadata,
  ApiMetadataCapable,
} from '@ahoo-wang/fetcher-decorator';
import {
  api,
  attribute,
  autoGeneratedError,
  body,
  get,
  path,
  post,
} from '@ahoo-wang/fetcher-decorator';

/**
 * Client for querying event streams through HTTP endpoints.
 * Implements EventStreamQueryApi to provide methods
 * for querying domain event streams with different query patterns.
 * This client supports counting, listing, streaming, and paging operations on event streams.
 *
 * @example
 * ```typescript
 * // Create client options configuration
 * const clientOptions: ApiMetadata = {
 *   fetcher: new Fetcher({ baseURL: 'http://localhost:8080/' }),
 *   basePath: 'owner/{ownerId}/cart'
 * };
 *
 * // Create an event stream query client instance
 * const eventStreamQueryClient = new EventStreamQueryClient(clientOptions);
 *
 * // Count event streams
 * const count = await eventStreamQueryClient.count(filter.matchAll());
 *
 * // List event streams
 * const listQuery: FilterListQuery = {
 *   filter: filter.matchAll()
 * };
 * const list = await eventStreamQueryClient.list(listQuery);
 *
 * // List event streams as stream
 * const listStream = await eventStreamQueryClient.listStream(listQuery);
 * for await (const event of listStream) {
 *   const domainEventStream = event.data;
 *   console.log('Received:', domainEventStream);
 * }
 *
 * // Paged event streams
 * const pagedQuery: FilterPagedQuery = {
 *   filter: filter.matchAll()
 * };
 * const paged = await eventStreamQueryClient.paged(pagedQuery);
 * ```
 */
@api()
export class EventStreamQueryClient<
  DomainEventBody = any,
  FIELDS extends string = string,
>
  implements EventStreamQueryApi<DomainEventBody, FIELDS>, ApiMetadataCapable
{
  /**
   * Creates a new EventStreamQueryClient instance.
   */
  constructor(public readonly apiMetadata?: ApiMetadata) {}

  /** Runs an event stream aggregation and returns all result rows. */
  @post(EventStreamQueryEndpointPaths.AGGREGATION)
  /* v8 ignore start */
  aggregate<
    Row extends DynamicDocument = DynamicDocument,
    AGGREGATION_FIELDS extends string = string,
  >(
    @body() query: AggregationQuery<FIELDS, AGGREGATION_FIELDS>,
    @attribute() attributes?: Record<string, unknown>,
    abort?: AbortController | AbortSignal,
  ): Promise<Row[]> {
    throw autoGeneratedError(query, attributes, abort);
  }
  /* v8 ignore stop */

  /** Runs an event stream aggregation and streams result rows as SSE. */
  @post(EventStreamQueryEndpointPaths.AGGREGATION, QUERY_STREAM_ENDPOINT)
  /* v8 ignore start */
  aggregateStream<
    Row extends DynamicDocument = DynamicDocument,
    AGGREGATION_FIELDS extends string = string,
  >(
    @body() query: AggregationQuery<FIELDS, AGGREGATION_FIELDS>,
    @attribute() attributes?: Record<string, unknown>,
    abort?: AbortController | AbortSignal,
  ): Promise<ReadableStream<JsonServerSentEvent<Row>>> {
    throw autoGeneratedError(query, attributes, abort);
  }
  /* v8 ignore stop */

  /** Retrieves the next cursor page of domain event streams. */
  @post(EventStreamQueryEndpointPaths.CURSOR)
  /* v8 ignore start */
  cursor<
    T extends Partial<DomainEventStream<DomainEventBody>> =
      DomainEventStream<DomainEventBody>,
  >(
    @body() query: CursorQuery<FIELDS>,
    @attribute() attributes?: Record<string, unknown>,
    abort?: AbortController | AbortSignal,
  ): Promise<CursorPage<T>> {
    throw autoGeneratedError(query, attributes, abort);
  }
  /* v8 ignore stop */

  /**
   * Counts the number of domain event streams that match the given filter.
   *
   * @param filter - The filter expression or legacy condition
   * @param attributes - Optional shared attributes that can be accessed by interceptors
   *                     throughout the request lifecycle. These attributes allow passing
   *                     custom data between different interceptors.
   * @param abort - Cancels the request: an `AbortController`, or an `AbortSignal` such as `AbortSignal.timeout(ms)` or the `signal` a data-fetching library passes.
   * @returns A promise that resolves to the count of matching event streams
   *
   * @example
   * ```typescript
   * const controller = new AbortController();
   * const count = await eventStreamQueryClient.count(filter.matchAll(), undefined, controller);
   * console.log('Total event streams:', count);
   *
   * // Cancel the request if needed
   * controller.abort();
   * ```
   */
  @post(EventStreamQueryEndpointPaths.COUNT)
  /* v8 ignore start */
  count(
    // compat(wow<9): accepts the deprecated Condition, which Wow < 8.11 needs; narrow to FilterExpression in v10.
    @body() filter: FilterExpression<FIELDS> | Condition<FIELDS>,
    @attribute() attributes?: Record<string, unknown>,
    abort?: AbortController | AbortSignal,
  ): Promise<number> {
    throw autoGeneratedError(filter, attributes, abort);
  }
  /* v8 ignore stop */

  /**
   * Retrieves a list of domain event streams based on the provided query parameters.
   *
   * @param listQuery - The query parameters for listing event streams
   * @param attributes - Optional shared attributes that can be accessed by interceptors
   *                     throughout the request lifecycle. These attributes allow passing
   *                     custom data between different interceptors.
   * @param abort - Cancels the request: an `AbortController`, or an `AbortSignal` such as `AbortSignal.timeout(ms)` or the `signal` a data-fetching library passes.
   * @returns A promise that resolves to an array of partial domain event streams
   *
   * @example
   * ```typescript
   * const controller = new AbortController();
   * const listQuery: FilterListQuery = {
   *   filter: filter.matchAll()
   * };
   * const list = await eventStreamQueryClient.list(listQuery, undefined, controller);
   * for (const domainEventStream of list) {
   *   console.log('Event stream:', domainEventStream);
   * }
   *
   * // Cancel the request if needed
   * controller.abort();
   * ```
   */
  @post(EventStreamQueryEndpointPaths.LIST)
  /* v8 ignore start */
  list<
    T extends Partial<DomainEventStream<DomainEventBody>> =
      DomainEventStream<DomainEventBody>,
  >(
    @body() listQuery: ListQueryRequest<FIELDS>,
    @attribute() attributes?: Record<string, unknown>,
    abort?: AbortController | AbortSignal,
  ): Promise<T[]> {
    throw autoGeneratedError(listQuery, attributes, abort);
  }
  /* v8 ignore stop */

  /**
   * Retrieves a stream of domain event streams based on the provided query parameters.
   * Sets the Accept header to text/event-stream to indicate that the response should be streamed.
   *
   * @param listQuery - The query parameters for listing event streams
   * @param attributes - Optional shared attributes that can be accessed by interceptors
   *                     throughout the request lifecycle. These attributes allow passing
   *                     custom data between different interceptors.
   * @param abort - Cancels the request: an `AbortController`, or an `AbortSignal` such as `AbortSignal.timeout(ms)` or the `signal` a data-fetching library passes.
   * @returns A promise that resolves to a readable stream of JSON server-sent events containing partial domain event streams
   *
   * @example
   * ```typescript
   * const controller = new AbortController();
   * const listQuery: FilterListQuery = {
   *   filter: filter.matchAll()
   * };
   * const listStream = await eventStreamQueryClient.listStream(listQuery, undefined, controller);
   * for await (const event of listStream) {
   *   const domainEventStream = event.data;
   *   console.log('Received event stream:', domainEventStream);
   * }
   *
   * // Cancel the request if needed
   * controller.abort();
   * ```
   */
  @post(EventStreamQueryEndpointPaths.LIST, QUERY_STREAM_ENDPOINT)
  /* v8 ignore start */
  listStream<
    T extends Partial<DomainEventStream<DomainEventBody>> =
      DomainEventStream<DomainEventBody>,
  >(
    @body() listQuery: ListQueryRequest<FIELDS>,
    @attribute() attributes?: Record<string, unknown>,
    abort?: AbortController | AbortSignal,
  ): Promise<ReadableStream<JsonServerSentEvent<T>>> {
    throw autoGeneratedError(listQuery, attributes, abort);
  }
  /* v8 ignore stop */

  /**
   * Retrieves a paged list of domain event streams based on the provided query parameters.
   *
   * @param pagedQuery - The query parameters for paging event streams
   * @param attributes - Optional shared attributes that can be accessed by interceptors
   *                     throughout the request lifecycle. These attributes allow passing
   *                     custom data between different interceptors.
   * @param abort - Cancels the request: an `AbortController`, or an `AbortSignal` such as `AbortSignal.timeout(ms)` or the `signal` a data-fetching library passes.
   * @returns A promise that resolves to a paged list of partial domain event streams
   *
   * @example
   * ```typescript
   * const controller = new AbortController();
   * const pagedQuery: FilterPagedQuery = {
   *   filter: filter.matchAll(),
   *   pagination: { index: 1, size: 10 }
   * };
   * const paged = await eventStreamQueryClient.paged(pagedQuery, undefined, controller);
   * console.log('Total:', paged.total);
   * for (const domainEventStream of paged.list) {
   *   console.log('Event stream:', domainEventStream);
   * }
   *
   * // Cancel the request if needed
   * controller.abort();
   * ```
   */
  @post(EventStreamQueryEndpointPaths.PAGED)
  /* v8 ignore start */
  paged<
    T extends Partial<DomainEventStream<DomainEventBody>> =
      DomainEventStream<DomainEventBody>,
  >(
    @body() pagedQuery: PagedQueryRequest<FIELDS>,
    @attribute() attributes?: Record<string, unknown>,
    abort?: AbortController | AbortSignal,
  ): Promise<PagedList<T>> {
    throw autoGeneratedError(pagedQuery, attributes, abort);
  }
  /* v8 ignore stop */

  /**
   * Loads one aggregate's event streams from `headVersion` to `tailVersion`,
   * both inclusive, in version order — how an audit trail or an event
   * sourcing view replays an aggregate. `GET {id}/event/{headVersion}/{tailVersion}`.
   *
   * The server treats the range as a list query: more than its maximum list
   * size (1000 by default) is refused. The route carries a tenant segment by
   * default but no owner segment, like the load-state routes.
   *
   * @param id - The aggregate id
   * @param headVersion - The first version, from 1
   * @param tailVersion - The last version
   * @param attributes - Optional shared attributes for the interceptors
   * @param abort - Cancels the request: an `AbortController`, or an `AbortSignal` such as `AbortSignal.timeout(ms)` or the `signal` a data-fetching library passes.
   * @returns The event streams of versions `headVersion` to `tailVersion`
   *
   * @example
   * ```typescript
   * const firstTen = await eventStreamQueryClient.load(cartId, 1, 10);
   * ```
   */
  @get(EventStreamQueryEndpointPaths.LOAD)
  /* v8 ignore start */
  load<
    T extends Partial<DomainEventStream<DomainEventBody>> =
      DomainEventStream<DomainEventBody>,
  >(
    @path('id') id: string,
    @path('headVersion') headVersion: number,
    @path('tailVersion') tailVersion: number,
    @attribute() attributes?: Record<string, unknown>,
    abort?: AbortController | AbortSignal,
  ): Promise<T[]> {
    throw autoGeneratedError(id, headVersion, tailVersion, attributes, abort);
  }
  /* v8 ignore stop */

  /**
   * {@link load} as a server-sent event stream, one event stream per event.
   * The stream errors with a `WowError` if the server fails midway.
   */
  @get(EventStreamQueryEndpointPaths.LOAD, QUERY_STREAM_ENDPOINT)
  /* v8 ignore start */
  loadStream<
    T extends Partial<DomainEventStream<DomainEventBody>> =
      DomainEventStream<DomainEventBody>,
  >(
    @path('id') id: string,
    @path('headVersion') headVersion: number,
    @path('tailVersion') tailVersion: number,
    @attribute() attributes?: Record<string, unknown>,
    abort?: AbortController | AbortSignal,
  ): Promise<ReadableStream<JsonServerSentEvent<T>>> {
    throw autoGeneratedError(id, headVersion, tailVersion, attributes, abort);
  }
  /* v8 ignore stop */
}
