// Code generated by wow-generator. DO NOT EDIT.

/** - key: example.ApiVersion */
export enum ApiVersion {
  V2 = 'V2',
  V3 = 'V3'
}

/**
 * - key: example.Link
 * - required: (none)
 */
export interface Link {
  href: string;
  templated: boolean;
}

/** - key: example.SecurityContext */
export type SecurityContext = globalThis.Record<string, any>;

/** - key: example.StringLinkMap */
export interface StringLinkMap {
  [key: string]: Link;
}

/** - key: example.StringObjectMap */
export type StringObjectMap = globalThis.Record<string, any>;

/** - key: example.StringStringListMap */
export interface StringStringListMap {
  [key: string]: string[];
}

/**
 * - key: example.WebServerNamespace
 * - required: (none)
 */
export interface WebServerNamespace {
  value: string;
}
