/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type {
  ApiMetadata,
  ApiMetadataCapable,
} from '@ahoo-wang/fetcher-decorator';
import {
  api,
  attribute,
  autoGeneratedError,
  get,
} from '@ahoo-wang/fetcher-decorator';
import type { WowMetadata } from './wowMetadata.js';

/**
 * Reads the server's `WowMetadata`: its bounded contexts, their aggregates,
 * and each aggregate's commands and events. `GET /wow/metadata`, relative to
 * the fetcher's base URL: construct it without a `basePath`, which would be
 * put in front of the path.
 *
 * @example
 * ```typescript
 * const metadata = await new WowMetadataClient().metadata();
 * Object.keys(metadata.contexts); // ['example-service', …]
 * ```
 */
@api()
export class WowMetadataClient implements ApiMetadataCapable {
  constructor(public readonly apiMetadata?: ApiMetadata) {}

  /**
   * @param attributes - Optional shared attributes for the interceptors
   * @param abort - Cancels the request: an `AbortController`, or an `AbortSignal` such as `AbortSignal.timeout(ms)` or the `signal` a data-fetching library passes.
   */
  @get('/wow/metadata')
  /* v8 ignore start */
  metadata(
    @attribute() attributes?: Record<string, unknown>,
    abort?: AbortController | AbortSignal,
  ): Promise<WowMetadata> {
    throw autoGeneratedError(attributes, abort);
  }
  /* v8 ignore stop */
}
