@startuml

!include layout.puml

left to right direction

title
ExecutionFailed State Flow
__State Diagram__
end title

state FAILED
state PREPARED
state ExecutionStatus <<choice>>
state SUCCEEDED
state COMPLETED #line.dotted;

[*] --> FAILED

FAILED --> PREPARED: PrepareCompensation
PREPARED --> ExecutionStatus: Execute
ExecutionStatus --> FAILED: ApplyExecutionFailed
ExecutionStatus --> SUCCEEDED: ApplyExecutionSuccess
SUCCEEDED --> COMPLETED
FAILED --> COMPLETED: MarkUnrecoverable

json CompletedCategory {
   "SUCCEEDED":"Succeeded",
   "UNRECOVERABLE":"Unrecoverable"
}

@enduml
