@startuml EventCompensation
!include layout.puml
title
Event Compensation Control
end title

left to right direction

actor Subscriber
actor Scheduler
actor Developer

package Query{
    usecase FindNextRetry as "FindNextRetry
    --
    !SUCCEEDED && retries<maxRetries
    --
    && nextRetryAt<=CurrentTime
    --
    && (FAILED || (PREPARED && timeoutAt<=CurrentTime))
    "
    usecase FindExecuting as "FindExecuting
    --
    PREPARED && timeoutAt > CurrentTime
    "
    usecase FindToRetry as "FindToRetry
    --
    !SUCCEEDED && retries<maxRetries
    --
    && (FAILED || (PREPARED && timeoutAt<=CurrentTime))"
    usecase FindNonRetryable as "FindNonRetryable
    --
    !SUCCEEDED
    --
    && retries>=maxRetries"
    usecase FindSuccess as "FindSuccess
    --
    SUCCEEDED"
    usecase Detail
    usecase History
}

package Command{
    usecase CreateExecutionFailed
    usecase PrepareCompensation
    usecase ForcePrepareCompensation
    usecase ApplyExecutionFailed
    usecase ApplyRetrySpec
    usecase ApplyExecutionSuccess
}

Subscriber --> CreateExecutionFailed
Subscriber --> ApplyExecutionFailed
Subscriber --> ApplyExecutionSuccess

Scheduler --> FindNextRetry
Scheduler --> PrepareCompensation

FindToRetry <-- Developer
FindExecuting <-- Developer
PrepareCompensation <-- Developer
ForcePrepareCompensation <-- Developer
ApplyRetrySpec <-- Developer
FindNonRetryable <-- Developer
FindSuccess <-- Developer
Detail <-- Developer
History <-- Developer
@enduml


