@startuml

!include layout.puml

title
Load Aggregate
__Sequence Diagram__
end title

participant AggregateRepository
participant SnapshotStore
participant AggregateFactory
participant StateAggregate
database Snapshot
database EventStore

autonumber "<b>[00]</b>"

[-> AggregateRepository++: load(aggregateId)
AggregateRepository -> SnapshotStore++: load(aggregateId)
SnapshotStore -> Snapshot++: load(aggregateId)
SnapshotStore <-- Snapshot--: snapshot

alt snapshot exist
    create StateAggregate
    SnapshotStore -> StateAggregate ++: deserialize snapshot to stateAggregate
    SnapshotStore <-- StateAggregate: stateAggregate
    AggregateRepository <-- SnapshotStore--: stateAggregate
else snapshot not exist
    AggregateRepository -> AggregateFactory++: create(aggregateId)
    create StateAggregate
    AggregateFactory -> StateAggregate ++: create(aggregateId)
    AggregateFactory <-- StateAggregate: stateAggregate
    AggregateRepository <-- AggregateFactory--: stateAggregate
end
AggregateRepository -> EventStore++: loadEventStream(aggregateId, aggregateVersion)
AggregateRepository <-- EventStore--:DomainEventStream
AggregateRepository -> StateAggregate:sourcing(DomainEventStream)
AggregateRepository <-- StateAggregate: stateAggregate
[<-- AggregateRepository: stateAggregate
@enduml
