@startuml

!include layout.puml

title
Send Command
__Sequence Diagram__
end title

actor User
participant CommandGateway
participant CommandValidator
participant IdempotencyChecker
participant WaitCoordinator
queue CommandQueue

CommandQueue++
User ++

autonumber "[00]"

User -> CommandGateway ++: sendAndWait(command,waitPlan)

CommandGateway -> CommandValidator++: verify(command)
CommandGateway <-- CommandValidator--: VerifyResult
alt verification failed
    User <-- CommandGateway: failed
else verification success
    CommandGateway -> IdempotencyChecker++: check(command)
    CommandGateway <-- IdempotencyChecker--: CheckResult
    alt check failed
        User <-- CommandGateway: failed
    else check success
        CommandGateway -> CommandQueue: emit(Command)
        CommandGateway <-- CommandQueue: Reactive result
        CommandGateway -> WaitCoordinator++: createLast/createStream(waitPlan)
        CommandGateway <-- WaitCoordinator--
        User <-- CommandGateway: Mono<Result>
    end
end
@enduml
