/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type { Fetcher } from '@ahoo-wang/fetcher';
import {
  CommandClient,
  CommandStage,
  waitStrategy,
} from '@ahoo-wang/wow-client';
import type { OrderCommands } from './orderActions.js';

// Step 4b: the commands, sent to the Wow service. A command client
// generated by wow-generator types each route and body; this one sends
// them by path.
export function wowOrderCommands(fetcher: Fetcher): OrderCommands {
  const client = new CommandClient({ fetcher, basePath: 'example/order' });
  // Answer once the snapshot is written: the engine reads the view again
  // right after `run` resolves, and must see the command's result.
  const headers = waitStrategy({ stage: CommandStage.SNAPSHOT });
  const send = async (path: string) => {
    // A refused command rejects (a `WowError`): the engine reports it on
    // that order, and the order stays selected.
    await client.send({ path, method: 'POST', headers, body: {} });
  };
  return {
    ship: orderId => send(`${orderId}/ship_order`),
    cancel: orderId => send(`${orderId}/cancel_order`),
  };
}
