// Code generated by wow-generator. DO NOT EDIT.

import { QueryClientFactory, type QueryClientOptions, ResourceAttributionPathSpec } from '@ahoo-wang/wow-client';
import { EXAMPLE_BOUNDED_CONTEXT_ALIAS } from '../boundedContext.js';
import type { AddressChanged, OrderAggregatedFields, OrderCreated, OrderPaid, OrderReceived, OrderShipped, WowExampleOrderState } from './types.js';

const DEFAULT_QUERY_CLIENT_OPTIONS: QueryClientOptions = {
  contextAlias: EXAMPLE_BOUNDED_CONTEXT_ALIAS,
  aggregateName: 'sales-order',
  resourceAttribution: ResourceAttributionPathSpec.TENANT,
};

export enum OrderDomainEventTypeMapTitle {
  address_changed = '收货地址已修改',
  order_created = 'order_created',
  order_paid = 'order_paid',
  order_received = 'order_received',
  order_shipped = 'order_shipped',
}

export type OrderDomainEventType = AddressChanged | OrderCreated | OrderPaid | OrderReceived | OrderShipped;

export const orderQueryClientFactory = new QueryClientFactory<WowExampleOrderState, `${OrderAggregatedFields}`, OrderDomainEventType>(DEFAULT_QUERY_CLIENT_OPTIONS);
