// Code generated by wow-generator. DO NOT EDIT.

/** - key: compensation.ApiVersion */
export enum ApiVersion {
  V2 = 'V2',
  V3 = 'V3'
}

/** - key: compensation.Link */
export interface Link {
  href: string;
  templated: boolean;
}

/** - key: compensation.SecurityContext */
export type SecurityContext = globalThis.Record<string, any>;

/** - key: compensation.StringLinkMap */
export interface StringLinkMap {
  [key: string]: Link;
}

/** - key: compensation.StringObjectMap */
export type StringObjectMap = globalThis.Record<string, any>;

/** - key: compensation.WebServerNamespace */
export interface WebServerNamespace {
  value: string;
}
