// Code generated by wow-generator. DO NOT EDIT.

/** - key: compensation.Link */
export interface Link {
  href: string;
  templated: boolean;
}

/** - key: compensation.StringLinkMap */
export interface StringLinkMap {
  [key: string]: Link;
}

/** - key: compensation.JsonNode */
export type JsonNode = any;
/** - key: compensation.StringObjectMap */
export type StringObjectMap = globalThis.Record<string, any>;

/** - key: compensation.StringStringListMap */
export interface StringStringListMap {
  [key: string]: string[];
}

/** - key: compensation.TimeUnit */
export enum TimeUnit {
  NANOSECONDS = 'NANOSECONDS',
  MICROSECONDS = 'MICROSECONDS',
  MILLISECONDS = 'MILLISECONDS',
  SECONDS = 'SECONDS',
  MINUTES = 'MINUTES',
  HOURS = 'HOURS',
  DAYS = 'DAYS'
}
