/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type {
  ApiMetadata,
  ApiMetadataCapable,
} from '@ahoo-wang/fetcher-decorator';
import type { LoadOwnerStateAggregateApi } from './loadOwnerStateAggregateApi.js';
import {
  api,
  attribute,
  autoGeneratedError,
  get,
  path,
} from '@ahoo-wang/fetcher-decorator';
import { LoadOwnerStateAggregateEndpointPaths } from './endpointPaths.js';
import { bindMethods } from '../../bindMethods.js';

/**
 * Loads the state of an aggregate whose ID is its owner's ID, such as a
 * user's cart (Wow's `AggregateRoute.Owner.AGGREGATE_ID`): `GET
 * {basePath}/state`, or the state at a version or a point in time. The owner
 * comes from the client's `urlParams`, not from the call. An aggregate that
 * does not exist or is deleted answers 404. Create it with
 * `QueryClientFactory.createLoadOwnerStateAggregateClient` and
 * `ResourceAttributionPathSpec.OWNER`.
 *
 * @template S - The type of the aggregate state
 *
 * @example
 * ```typescript
 * const carts = new LoadOwnerStateAggregateClient<{ items: string[] }>({
 *   basePath: 'owner/{ownerId}/cart',
 *   urlParams: { path: { ownerId: 'user-1' } },
 * });
 * const cart = await carts.load();
 * ```
 */
@api()
export class LoadOwnerStateAggregateClient<S>
  implements LoadOwnerStateAggregateApi<S>, ApiMetadataCapable
{
  constructor(public readonly apiMetadata?: ApiMetadata) {
    bindMethods(this);
  }

  /**
   * Loads the current state of the aggregate.
   *
   * @param attributes - Optional shared attributes that can be accessed by interceptors
   *                     throughout the request lifecycle. These attributes allow passing
   *                     custom data between different interceptors.
   * @param abort - Cancels the request: an `AbortController`, or an `AbortSignal` such as `AbortSignal.timeout(ms)` or the `signal` a data-fetching library passes.
   * @returns A promise that resolves to the current state of the aggregate
   */
  @get(LoadOwnerStateAggregateEndpointPaths.LOAD)
  /* v8 ignore start */
  load(
    @attribute() attributes?: Record<string, unknown>,
    abort?: AbortController | AbortSignal,
  ): Promise<S> {
    throw autoGeneratedError(attributes, abort);
  }
  /* v8 ignore stop */

  /**
   * Loads the state of the aggregate at a specific version.
   *
   * @param version - The version number of the aggregate state to load
   * @param attributes - Optional shared attributes that can be accessed by interceptors
   *                     throughout the request lifecycle. These attributes allow passing
   *                     custom data between different interceptors.
   * @param abort - Cancels the request: an `AbortController`, or an `AbortSignal` such as `AbortSignal.timeout(ms)` or the `signal` a data-fetching library passes.
   * @returns A promise that resolves to the state of the aggregate at the specified version
   */
  @get(LoadOwnerStateAggregateEndpointPaths.LOAD_VERSIONED)
  /* v8 ignore start */
  loadVersioned(
    @path('version') version: number,
    @attribute() attributes?: Record<string, unknown>,
    abort?: AbortController | AbortSignal,
  ): Promise<S> {
    throw autoGeneratedError(version, attributes, abort);
  }
  /* v8 ignore stop */

  /**
   * Loads the state of the aggregate at a specific point in time.
   *
   * @param createTime - The creation timestamp to load the aggregate state for
   * @param attributes - Optional shared attributes that can be accessed by interceptors
   *                     throughout the request lifecycle. These attributes allow passing
   *                     custom data between different interceptors.
   * @param abort - Cancels the request: an `AbortController`, or an `AbortSignal` such as `AbortSignal.timeout(ms)` or the `signal` a data-fetching library passes.
   * @returns A promise that resolves to the state of the aggregate at the specified time
   */
  @get(LoadOwnerStateAggregateEndpointPaths.LOAD_TIME_BASED)
  /* v8 ignore start */
  loadTimeBased(
    @path('createTime') createTime: number,
    @attribute() attributes?: Record<string, unknown>,
    abort?: AbortController | AbortSignal,
  ): Promise<S> {
    throw autoGeneratedError(createTime, attributes, abort);
  }
  /* v8 ignore stop */
}
