/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type {
  ApiMetadata,
  ApiMetadataCapable,
} from '@ahoo-wang/fetcher-decorator';
import type { LoadStateAggregateApi } from './loadStateAggregateApi.js';
import {
  api,
  attribute,
  autoGeneratedError,
  get,
  path,
} from '@ahoo-wang/fetcher-decorator';
import { LoadStateAggregateEndpointPaths } from './endpointPaths.js';

@api()
export class LoadStateAggregateClient<S>
  implements LoadStateAggregateApi<S>, ApiMetadataCapable
{
  constructor(public readonly apiMetadata?: ApiMetadata) {}

  /**
   * Loads the current state of the aggregate by its ID.
   *
   * @param id - The unique identifier of the aggregate to load
   * @param attributes - Optional shared attributes that can be accessed by interceptors
   *                     throughout the request lifecycle. These attributes allow passing
   *                     custom data between different interceptors.
   * @param abort - Cancels the request: an `AbortController`, or an `AbortSignal` such as `AbortSignal.timeout(ms)` or the `signal` a data-fetching library passes.
   * @returns A promise that resolves to the current state of the aggregate
   */
  @get(LoadStateAggregateEndpointPaths.LOAD)
  /* v8 ignore start */
  load(
    @path('id') id: string,
    @attribute() attributes?: Record<string, unknown>,
    abort?: AbortController | AbortSignal,
  ): Promise<S> {
    throw autoGeneratedError(id, attributes, abort);
  }
  /* v8 ignore stop */

  /**
   * Loads the state of the aggregate at a specific version by its ID.
   *
   * @param id - The unique identifier of the aggregate to load
   * @param version - The version number of the aggregate state to load
   * @param attributes - Optional shared attributes that can be accessed by interceptors
   *                     throughout the request lifecycle. These attributes allow passing
   *                     custom data between different interceptors.
   * @param abort - Cancels the request: an `AbortController`, or an `AbortSignal` such as `AbortSignal.timeout(ms)` or the `signal` a data-fetching library passes.
   * @returns A promise that resolves to the state of the aggregate at the specified version
   */
  @get(LoadStateAggregateEndpointPaths.LOAD_VERSIONED)
  /* v8 ignore start */
  loadVersioned(
    @path('id') id: string,
    @path('version') version: number,
    @attribute() attributes?: Record<string, unknown>,
    abort?: AbortController | AbortSignal,
  ): Promise<S> {
    throw autoGeneratedError(id, version, attributes, abort);
  }
  /* v8 ignore stop */

  /**
   * Loads the state of the aggregate at a specific point in time by its ID.
   *
   * @param id - The unique identifier of the aggregate to load
   * @param createTime - The creation timestamp to load the aggregate state for
   * @param attributes - Optional shared attributes that can be accessed by interceptors
   *                     throughout the request lifecycle. These attributes allow passing
   *                     custom data between different interceptors.
   * @param abort - Cancels the request: an `AbortController`, or an `AbortSignal` such as `AbortSignal.timeout(ms)` or the `signal` a data-fetching library passes.
   * @returns A promise that resolves to the state of the aggregate at the specified time
   */
  @get(LoadStateAggregateEndpointPaths.LOAD_TIME_BASED)
  /* v8 ignore start */
  loadTimeBased(
    @path('id') id: string,
    @path('createTime') createTime: number,
    @attribute() attributes?: Record<string, unknown>,
    abort?: AbortController | AbortSignal,
  ): Promise<S> {
    throw autoGeneratedError(id, createTime, attributes, abort);
  }
  /* v8 ignore stop */
}
