/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Probes of the generated modules: every import written out, relative
 * imports that NodeNext resolves, and the marker every file starts with.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { NODE_NEXT_OPTIONS, typeCheck } from '../support/generation';
import { generateCompiling, sharedGeneration } from '../support/probes';
import { wowDocument } from '../support/specs';

/** The Wow document most probes of this file read, generated once. */
const wow = sharedGeneration(() => generateCompiling(wowDocument()));

describe('imports do not depend on the output directory', () => {
  it('writes every import explicitly, so a cold directory compiles', async () => {
    const { read } = await wow();
    const commandClient = read('shop/order/commandClient.ts');
    expect(commandClient).toContain(
      "import { SHOP_BOUNDED_CONTEXT_ALIAS } from '../boundedContext.js';",
    );
  });
});

describe('relative imports carry .js', () => {
  it('compiles under NodeNext', async () => {
    const { dir, read } = await wow();
    expect(read('index.ts')).toContain("export * from './shop/index.js';");
    expect(typeCheck(dir, NODE_NEXT_OPTIONS)).toEqual([]);
  });

  it('is what NodeNext checks: an extensionless import fails there', async () => {
    const { dir, output } = await generateCompiling(wowDocument());
    const index = join(output, 'index.ts');
    writeFileSync(
      index,
      readFileSync(index, 'utf8').replace('./shop/index.js', './shop'),
    );
    expect(typeCheck(dir, NODE_NEXT_OPTIONS).join('\n')).toContain('TS2834');
  });
});

describe('generated files', () => {
  it('start with the generated-code marker and use single quotes', async () => {
    const { read } = await wow();
    const client = read('shop/order/commandClient.ts');
    expect(
      client.startsWith('// Code generated by wow-generator. DO NOT EDIT.\n'),
    ).toBe(true);
    expect(client).not.toContain('"');
    expect(read('shop/order/types.ts')).not.toContain('```json');
  });
});
