spring:
  application:
    name: order-service
  #  autoconfigure:
  #    exclude: org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration
  data:
    mongodb:
      host: localhost
      database: order_db
      username: root
      password: root
      authentication-database: admin
#  r2dbc:
#    url: r2dbc:pool:mariadb://root:root@localhost:3306/wow_db?initialSize=8&maxSize=8&acquireRetry=3&maxLifeTime=PT30M
logging:
  level:
    #    root: debug
    me.ahoo.wow: debug
    org.springframework.r2dbc: trace # for queries

cosid:
  machine:
    enabled: true
    distributor:
      type: mongo
  generator:
    enabled: true
#  snowflake:
#    enabled: true
#    provider:
#      "[order-service.order]":
#        converter:
#          type: radix
wow:
  command:
    bus:
      type: in_memory
  event:
    bus:
      type: in_memory
  kafka:
    enabled: false
#    bootstrap-servers: 'PLAINTEXT://localhost:63081'
#  eventsourcing:
#    snapshot:
#      strategy: all
#      storage: mongo
#  r2dbc:
#    datasource:
#      type: sharding
#      sharding:
#        databases:
#          event_stream_0:
#            url: r2dbc:pool:mariadb://root:root@localhost:3306/event_stream_0?initialSize=8&maxSize=8&acquireRetry=3&maxLifeTime=PT30M
#          event_stream_1:
#            url: r2dbc:pool:mariadb://root:root@localhost:3306/event_stream_1?initialSize=8&maxSize=8&acquireRetry=3&maxLifeTime=PT30M
#          snapshot_0:
#            url: r2dbc:pool:mariadb://root:root@localhost:3306/snapshot_0?initialSize=8&maxSize=8&acquireRetry=3&maxLifeTime=PT30M
#          snapshot_1:
#            url: r2dbc:pool:mariadb://root:root@localhost:3306/snapshot_1?initialSize=8&maxSize=8&acquireRetry=3&maxLifeTime=PT30M
#        event-stream:
#          order:
#            database-algorithm: event_stream_db
#            table-algorithm: order_event_stream_table
#        snapshot:
#          order:
#            database-algorithm: snapshot_db
#            table-algorithm: order_snapshot_table
#        algorithms:
#          event_stream_db:
#            type: mod
#            mod:
#              logic-name-prefix: event_stream_
#              divisor: 2
#          snapshot_db:
#            type: mod
#            mod:
#              logic-name-prefix: snapshot_
#              divisor: 2
#          order_event_stream_table:
#            type: mod
#            mod:
#              logic-name-prefix: order_event_stream_
#              divisor: 4
#          order_snapshot_table:
#            type: mod
#            mod:
#              logic-name-prefix: order_snapshot_
#              divisor: 4