server:
  http2:
    enabled: true
  compression:
    enabled: true
management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - cosid
          - cosidGenerator
          - cosidStringGenerator
          - threaddump

springdoc:
  show-actuator: true
  api-docs:
    version: openapi-3-1

#SPRING_AUTOCONFIGURE_EXCLUDE=org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchClientAutoConfiguration,org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchRestClientAutoConfiguration,org.springframework.boot.autoconfigure.elasticsearch.ReactiveElasticsearchClientAutoConfiguration
#SPRING_DATA_MONGODB_URI=mongodb://root:root@localhost:27017/wow_example_db?authSource=admin&maxIdleTimeMS=60000
#WOW_EVENTSOURCING_STORE_STORAGE=mongo
#WOW_EVENTSOURCING_SNAPSHOT_STORAGE=mongo

spring:
  application:
    name: example-service
  jackson:
    mapper:
      accept-case-insensitive-enums: true
    datatype:
      datetime:
        write-durations-as-timestamps: true
        write-dates-as-timestamps: true
  autoconfigure:
    exclude:
#      - org.springframework.boot.mongodb.autoconfigure.MongoAutoConfiguration
#      - org.springframework.boot.mongodb.autoconfigure.MongoReactiveAutoConfiguration
      - org.springframework.boot.elasticsearch.autoconfigure.ElasticsearchClientAutoConfiguration
      - org.springframework.boot.elasticsearch.autoconfigure.ElasticsearchRestClientAutoConfiguration
  mongodb:
    uri: mongodb://root:root@localhost:27017/wow_example_db?authSource=admin&maxIdleTimeMS=60000
  

logging:
  level:
    #    root: debug
    me.ahoo.wow: INFO
#springdoc:
#  remove-broken-reference-definitions: false
cosid:
  machine:
    enabled: true
    distributor:
      type: manual
      manual:
        machine-id: 1
  generator:
    enabled: true
#  snowflake:
#    enabled: true
#    provider:
#      order:
#        converter:
#          type: radix
wow:
  bi:
    script:
      enabled: true
      consumer-group-namespace: example-service-local
      inspector:
        type: NO_OP
  command:
    bus:
      type: in_memory
#      local-first:
#        enabled: false
  event:
    bus:
      type: in_memory
  kafka:
    enabled: false
    bootstrap-servers: 'PLAINTEXT://localhost:61546'

  eventsourcing:
    store:
      storage: mongo
    snapshot:
      storage: mongo
    state:
      bus:
        type: in_memory
